{{
    config(
        materialized='table',
        tags=['analytics', 'orders', 'weekly'],
        description='Cohort analysis by first order date'
    )
}}

WITH first_orders AS (
    SELECT
        CUSTOMER_ID,
        MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
        DATE_TRUNC('MONTH', MIN(ORDER_DATE)) AS COHORT_MONTH,
        DATE_TRUNC('WEEK', MIN(ORDER_DATE)) AS COHORT_WEEK,
        MIN(RESTAURANT_ID) AS FIRST_RESTAURANT_ID,
        MIN(TOTAL_AMOUNT) AS FIRST_ORDER_AMOUNT
    FROM {{ ref('fact_order') }}
    GROUP BY CUSTOMER_ID
),

cohort_orders AS (
    SELECT
        f.CUSTOMER_ID,
        f.COHORT_MONTH,
        f.COHORT_WEEK,
        f.FIRST_ORDER_DATE,
        f.FIRST_RESTAURANT_ID,
        f.FIRST_ORDER_AMOUNT,
        o.ORDER_ID,
        o.ORDER_DATE,
        o.TOTAL_AMOUNT,
        o.RESTAURANT_ID,
        DATE_TRUNC('MONTH', o.ORDER_DATE) AS ORDER_MONTH,
        DATEDIFF(MONTH, f.COHORT_MONTH, DATE_TRUNC('MONTH', o.ORDER_DATE)) AS MONTHS_SINCE_FIRST_ORDER,
        DATEDIFF(DAY, f.FIRST_ORDER_DATE, o.ORDER_DATE) AS DAYS_SINCE_FIRST_ORDER,
        ROW_NUMBER() OVER (PARTITION BY f.CUSTOMER_ID ORDER BY o.ORDER_DATE) AS ORDER_NUMBER
    FROM first_orders f
    INNER JOIN {{ ref('fact_order') }} o
        ON f.CUSTOMER_ID = o.CUSTOMER_ID
)

SELECT
    co.COHORT_MONTH,
    co.ORDER_MONTH,
    co.MONTHS_SINCE_FIRST_ORDER,

    -- Cohort Size
    COUNT(DISTINCT CASE WHEN co.ORDER_NUMBER = 1 THEN co.CUSTOMER_ID END) AS COHORT_SIZE,

    -- Activity Metrics
    COUNT(DISTINCT co.CUSTOMER_ID) AS ACTIVE_CUSTOMERS,
    COUNT(DISTINCT co.ORDER_ID) AS TOTAL_ORDERS,
    SUM(co.TOTAL_AMOUNT) AS TOTAL_REVENUE,

    -- Retention Rate
    DIV0(
        COUNT(DISTINCT co.CUSTOMER_ID),
        COUNT(DISTINCT CASE WHEN co.ORDER_NUMBER = 1 THEN co.CUSTOMER_ID END)
    ) * 100 AS RETENTION_RATE,

    -- Average Metrics
    AVG(co.TOTAL_AMOUNT) AS AVG_ORDER_VALUE,
    DIV0(COUNT(DISTINCT co.ORDER_ID), COUNT(DISTINCT co.CUSTOMER_ID)) AS ORDERS_PER_CUSTOMER,
    DIV0(SUM(co.TOTAL_AMOUNT), COUNT(DISTINCT co.CUSTOMER_ID)) AS REVENUE_PER_CUSTOMER,

    -- First Order Characteristics
    AVG(co.FIRST_ORDER_AMOUNT) AS AVG_FIRST_ORDER_AMOUNT,

    -- Restaurant Loyalty
    SUM(CASE WHEN co.RESTAURANT_ID = co.FIRST_RESTAURANT_ID THEN 1 ELSE 0 END) AS ORDERS_FROM_FIRST_RESTAURANT,
    DIV0(
        SUM(CASE WHEN co.RESTAURANT_ID = co.FIRST_RESTAURANT_ID THEN 1 ELSE 0 END),
        COUNT(DISTINCT co.ORDER_ID)
    ) * 100 AS FIRST_RESTAURANT_LOYALTY_RATE,

    -- Cumulative Metrics
    SUM(SUM(co.TOTAL_AMOUNT)) OVER (
        PARTITION BY co.COHORT_MONTH
        ORDER BY co.MONTHS_SINCE_FIRST_ORDER
    ) AS CUMULATIVE_COHORT_REVENUE,

    -- Order Frequency
    AVG(co.DAYS_SINCE_FIRST_ORDER) AS AVG_DAYS_FROM_FIRST_ORDER,

    CURRENT_TIMESTAMP() AS CREATED_AT

FROM cohort_orders co
GROUP BY
    co.COHORT_MONTH,
    co.ORDER_MONTH,
    co.MONTHS_SINCE_FIRST_ORDER