{{
config(
materialized='table',
tags=['analytics', 'orders', 'restaurant', 'daily'],
description='Restaurant performance through order lens'
)
}}WITH restaurant_order_metrics AS (
SELECT
o.RESTAURANT_ID,
DATE_TRUNC('DAY', o.ORDER_DATE) AS ORDER_DAY,
DATE_TRUNC('WEEK', o.ORDER_DATE) AS ORDER_WEEK,
DATE_TRUNC('MONTH', o.ORDER_DATE) AS ORDER_MONTH,    COUNT(DISTINCT o.ORDER_ID) AS DAILY_ORDERS,
    SUM(o.TOTAL_AMOUNT) AS DAILY_REVENUE,
    AVG(o.TOTAL_AMOUNT) AS AVG_ORDER_VALUE,
    COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,    SUM(CASE WHEN o.CURRENT_STATUS = 'COMPLETED' THEN 1 ELSE 0 END) AS COMPLETED_ORDERS,
    SUM(CASE WHEN o.CURRENT_STATUS = 'CANCELLED' THEN 1 ELSE 0 END) AS CANCELLED_ORDERS,    AVG(DATEDIFF(MINUTE, o.CREATED_AT, o.STATUS_UPDATED_AT)) AS AVG_PROCESSING_TIME
FROM {{ ref('fact_order') }} o
GROUP BY
    o.RESTAURANT_ID,
    DATE_TRUNC('DAY', o.ORDER_DATE),
    DATE_TRUNC('WEEK', o.ORDER_DATE),
    DATE_TRUNC('MONTH', o.ORDER_DATE)
)SELECT
rom.RESTAURANT_ID,
r.RESTAURANT_NAME,
r.CUISINE_TYPE,
r.PRICING_FOR_TWO,
r.LOCALITY,
l.CITY,
l.STATE,
l.CITY_TIER,rom.ORDER_DAY,
rom.ORDER_WEEK,
rom.ORDER_MONTH,-- Daily Metrics
rom.DAILY_ORDERS,
rom.DAILY_REVENUE,
rom.AVG_ORDER_VALUE,
rom.UNIQUE_CUSTOMERS,
rom.COMPLETED_ORDERS,
rom.CANCELLED_ORDERS,
rom.AVG_PROCESSING_TIME,-- Rates
DIV0(rom.COMPLETED_ORDERS, rom.DAILY_ORDERS) * 100 AS COMPLETION_RATE,
DIV0(rom.CANCELLED_ORDERS, rom.DAILY_ORDERS) * 100 AS CANCELLATION_RATE,
DIV0(rom.UNIQUE_CUSTOMERS, rom.DAILY_ORDERS) AS CUSTOMER_REPEAT_RATIO,-- Moving Averages (7-day)
AVG(rom.DAILY_ORDERS) OVER (
    PARTITION BY rom.RESTAURANT_ID
    ORDER BY rom.ORDER_DAY
    ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
) AS MA7_ORDERS,AVG(rom.DAILY_REVENUE) OVER (
    PARTITION BY rom.RESTAURANT_ID
    ORDER BY rom.ORDER_DAY
    ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
) AS MA7_REVENUE,-- Growth Metrics
LAG(rom.DAILY_ORDERS, 7) OVER (
    PARTITION BY rom.RESTAURANT_ID
    ORDER BY rom.ORDER_DAY
) AS ORDERS_SAME_DAY_LAST_WEEK,DIV0(
    (rom.DAILY_ORDERS - LAG(rom.DAILY_ORDERS, 7) OVER (
        PARTITION BY rom.RESTAURANT_ID
        ORDER BY rom.ORDER_DAY
    )),
    LAG(rom.DAILY_ORDERS, 7) OVER (
        PARTITION BY rom.RESTAURANT_ID
        ORDER BY rom.ORDER_DAY
    )
) * 100 AS WOW_ORDER_GROWTH_PCT,-- Cumulative Metrics
SUM(rom.DAILY_ORDERS) OVER (
    PARTITION BY rom.RESTAURANT_ID, rom.ORDER_MONTH
    ORDER BY rom.ORDER_DAY
) AS MTD_ORDERS,SUM(rom.DAILY_REVENUE) OVER (
    PARTITION BY rom.RESTAURANT_ID, rom.ORDER_MONTH
    ORDER BY rom.ORDER_DAY
) AS MTD_REVENUE,-- Ranking
DENSE_RANK() OVER (
    PARTITION BY rom.ORDER_DAY, l.CITY
    ORDER BY rom.DAILY_ORDERS DESC
) AS CITY_DAILY_ORDER_RANK,DENSE_RANK() OVER (
    PARTITION BY rom.ORDER_DAY, l.CITY
    ORDER BY rom.DAILY_REVENUE DESC
) AS CITY_DAILY_REVENUE_RANK,-- Performance Classification
CASE
    WHEN rom.DAILY_ORDERS >= 50 AND rom.DAILY_REVENUE >= 25000 THEN 'TOP_PERFORMER'
    WHEN rom.DAILY_ORDERS >= 20 AND rom.DAILY_REVENUE >= 10000 THEN 'HIGH_PERFORMER'
    WHEN rom.DAILY_ORDERS >= 10 THEN 'AVERAGE_PERFORMER'
    ELSE 'LOW_PERFORMER'
END AS PERFORMANCE_TIER,CURRENT_TIMESTAMP() AS CREATED_ATFROM restaurant_order_metrics rom
LEFT JOIN {{ ref('dim_restaurant') }} r
ON rom.RESTAURANT_ID = r.RESTAURANT_ID
LEFT JOIN {{ ref('dim_location') }} l
ON r.LOCATION_ID = l.LOCATION_ID
