{{
    config(
        materialized='table',
        tags=['analytics', 'orders', 'daily'],
        description='Customer ordering journey and behavior analysis'
    )
}}

WITH customer_order_sequence AS (
    SELECT
        o.ORDER_ID,
        o.CUSTOMER_ID,
        o.ORDER_DATE,
        o.TOTAL_AMOUNT,
        o.RESTAURANT_ID,
        o.PAYMENT_METHOD,
        o.CURRENT_STATUS,
        ROW_NUMBER() OVER (
            PARTITION BY o.CUSTOMER_ID
            ORDER BY o.ORDER_DATE
        ) AS ORDER_SEQUENCE_NUMBER,
        LAG(o.ORDER_DATE) OVER (
            PARTITION BY o.CUSTOMER_ID
            ORDER BY o.ORDER_DATE
        ) AS PREVIOUS_ORDER_DATE,
        LAG(o.RESTAURANT_ID) OVER (
            PARTITION BY o.CUSTOMER_ID
            ORDER BY o.ORDER_DATE
        ) AS PREVIOUS_RESTAURANT_ID,
        LAG(o.TOTAL_AMOUNT) OVER (
            PARTITION BY o.CUSTOMER_ID
            ORDER BY o.ORDER_DATE
        ) AS PREVIOUS_ORDER_AMOUNT,
        LEAD(o.ORDER_DATE) OVER (
            PARTITION BY o.CUSTOMER_ID
            ORDER BY o.ORDER_DATE
        ) AS NEXT_ORDER_DATE
    FROM {{ ref('fact_order') }} o
)

SELECT
    cos.ORDER_ID,
    cos.CUSTOMER_ID,
    c.NAME AS CUSTOMER_NAME,
    c.GENDER,
    DATEDIFF(YEAR, c.DOB, cos.ORDER_DATE) AS CUSTOMER_AGE_AT_ORDER,
    cos.ORDER_DATE,
    cos.TOTAL_AMOUNT,
    cos.CURRENT_STATUS,

    -- Restaurant Information
    cos.RESTAURANT_ID,
    r.RESTAURANT_NAME,
    r.CUISINE_TYPE,

    -- Location
    l.CITY,
    l.STATE,

    -- Order Sequence Metrics
    cos.ORDER_SEQUENCE_NUMBER,
    CASE
        WHEN cos.ORDER_SEQUENCE_NUMBER = 1 THEN 'FIRST_ORDER'
        WHEN cos.ORDER_SEQUENCE_NUMBER = 2 THEN 'SECOND_ORDER'
        WHEN cos.ORDER_SEQUENCE_NUMBER <= 5 THEN 'EARLY_ORDERS'
        WHEN cos.ORDER_SEQUENCE_NUMBER <= 10 THEN 'REGULAR_CUSTOMER'
        ELSE 'LOYAL_CUSTOMER'
    END AS CUSTOMER_JOURNEY_STAGE,

    -- Inter-Order Behavior
    DATEDIFF(DAY, cos.PREVIOUS_ORDER_DATE, cos.ORDER_DATE) AS DAYS_SINCE_LAST_ORDER,
    CASE
        WHEN DATEDIFF(DAY, cos.PREVIOUS_ORDER_DATE, cos.ORDER_DATE) <= 1 THEN 'SAME_DAY'
        WHEN DATEDIFF(DAY, cos.PREVIOUS_ORDER_DATE, cos.ORDER_DATE) <= 7 THEN 'WITHIN_WEEK'
        WHEN DATEDIFF(DAY, cos.PREVIOUS_ORDER_DATE, cos.ORDER_DATE) <= 30 THEN 'WITHIN_MONTH'
        WHEN DATEDIFF(DAY, cos.PREVIOUS_ORDER_DATE, cos.ORDER_DATE) <= 90 THEN 'WITHIN_QUARTER'
        ELSE 'REACTIVATED'
    END AS ORDER_FREQUENCY_TYPE,

    -- Restaurant Loyalty
    CASE
        WHEN cos.RESTAURANT_ID = cos.PREVIOUS_RESTAURANT_ID THEN 1
        ELSE 0
    END AS IS_REPEAT_RESTAURANT,

    COUNT(DISTINCT cos.RESTAURANT_ID) OVER (
        PARTITION BY cos.CUSTOMER_ID
        ORDER BY cos.ORDER_DATE
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS RESTAURANTS_TRIED_TO_DATE,

    -- Spending Behavior
    cos.PREVIOUS_ORDER_AMOUNT,
    cos.TOTAL_AMOUNT - COALESCE(cos.PREVIOUS_ORDER_AMOUNT, 0) AS ORDER_AMOUNT_CHANGE,
    CASE
        WHEN cos.TOTAL_AMOUNT > COALESCE(cos.PREVIOUS_ORDER_AMOUNT, 0) THEN 'INCREASED'
        WHEN cos.TOTAL_AMOUNT < COALESCE(cos.PREVIOUS_ORDER_AMOUNT, 0) THEN 'DECREASED'
        WHEN cos.PREVIOUS_ORDER_AMOUNT IS NULL THEN 'FIRST_ORDER'
        ELSE 'SAME'
    END AS SPENDING_TREND,

    -- Running Totals
    SUM(cos.TOTAL_AMOUNT) OVER (
        PARTITION BY cos.CUSTOMER_ID
        ORDER BY cos.ORDER_DATE
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS CUMULATIVE_SPEND,

    AVG(cos.TOTAL_AMOUNT) OVER (
        PARTITION BY cos.CUSTOMER_ID
        ORDER BY cos.ORDER_DATE
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_ORDER_VALUE_TO_DATE,

    -- Churn Risk Indicators
    DATEDIFF(DAY, cos.ORDER_DATE, cos.NEXT_ORDER_DATE) AS DAYS_UNTIL_NEXT_ORDER,
    CASE
        WHEN cos.NEXT_ORDER_DATE IS NULL
            AND DATEDIFF(DAY, cos.ORDER_DATE, CURRENT_DATE()) > 90
        THEN 'HIGH_CHURN_RISK'
        WHEN cos.NEXT_ORDER_DATE IS NULL
            AND DATEDIFF(DAY, cos.ORDER_DATE, CURRENT_DATE()) > 30
        THEN 'MEDIUM_CHURN_RISK'
        WHEN cos.NEXT_ORDER_DATE IS NULL THEN 'LOW_CHURN_RISK'
        ELSE 'RETURNED'
    END AS CHURN_RISK_LEVEL,

    -- Payment Method Consistency
    cos.PAYMENT_METHOD,
    COUNT(DISTINCT cos.PAYMENT_METHOD) OVER (
        PARTITION BY cos.CUSTOMER_ID
        ORDER BY cos.ORDER_DATE
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS PAYMENT_METHODS_USED_TO_DATE,

    -- Time Patterns
    HOUR(cos.ORDER_DATE) AS ORDER_HOUR,
    CASE
        WHEN HOUR(cos.ORDER_DATE) BETWEEN 6 AND 11 THEN 'MORNING'
        WHEN HOUR(cos.ORDER_DATE) BETWEEN 12 AND 16 THEN 'AFTERNOON'
        WHEN HOUR(cos.ORDER_DATE) BETWEEN 17 AND 21 THEN 'EVENING'
        ELSE 'NIGHT'
    END AS TIME_OF_DAY,

    CURRENT_TIMESTAMP() AS CREATED_AT

FROM customer_order_sequence cos
LEFT JOIN {{ ref('dim_customer') }} c
    ON cos.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN {{ ref('dim_restaurant') }} r
    ON cos.RESTAURANT_ID = r.RESTAURANT_ID
LEFT JOIN {{ ref('dim_location') }} l
ON r.LOCATION_ID = l.LOCATION_ID