{{
    config(
        materialized='table',
        tags=['analytics', 'orders', 'daily'],
        description='Order fulfillment performance and delivery analysis'
    )
}}

SELECT
    o.ORDER_ID,
    o.ORDER_DATE,
    o.CUSTOMER_ID,
    c.NAME AS CUSTOMER_NAME,
    o.RESTAURANT_ID,
    r.RESTAURANT_NAME,
    r.CUISINE_TYPE,
    o.TOTAL_AMOUNT,
    o.CURRENT_STATUS AS ORDER_STATUS,

    -- Delivery Information
    fd.DELIVERY_ID,
    fd.DELIVERY_AGENT_ID,
    da.DELIVERY_AGENT_NAME,
    da.VEHICLE_TYPE,
    da.RATING AS AGENT_RATING,
    fd.DELIVERY_DATE,
    fd.CURRENT_STATUS AS DELIVERY_STATUS,

    -- Customer Address
    ca.LOCALITY AS DELIVERY_LOCALITY,
    ca.CITY AS DELIVERY_CITY,
    ca.ZIPCODE AS DELIVERY_ZIPCODE,
    ca.ADDRESS_TYPE,

    -- Restaurant Location
    r.LOCALITY AS RESTAURANT_LOCALITY,
    l.CITY AS RESTAURANT_CITY,

    -- Time Metrics
    TRY_CAST(REGEXP_REPLACE(fd.ESTIMATED_TIME, '[^0-9]', '') AS INTEGER) AS ESTIMATED_DELIVERY_TIME_MINS,
    DATEDIFF(MINUTE, o.ORDER_DATE, fd.DELIVERY_DATE) AS ACTUAL_DELIVERY_TIME_MINS,
    DATEDIFF(MINUTE, o.CREATED_AT, o.STATUS_UPDATED_AT) AS ORDER_PROCESSING_TIME_MINS,
    DATEDIFF(MINUTE, fd.CREATED_AT, fd.STATUS_UPDATED_AT) AS DELIVERY_PROCESSING_TIME_MINS,

    -- Time Variance
    DATEDIFF(MINUTE, o.ORDER_DATE, fd.DELIVERY_DATE) -
        TRY_CAST(REGEXP_REPLACE(fd.ESTIMATED_TIME, '[^0-9]', '') AS INTEGER) AS DELIVERY_TIME_VARIANCE_MINS,

    -- Performance Classifications
    CASE
        WHEN DATEDIFF(MINUTE, o.ORDER_DATE, fd.DELIVERY_DATE) <=
            TRY_CAST(REGEXP_REPLACE(fd.ESTIMATED_TIME, '[^0-9]', '') AS INTEGER)
        THEN 'ON_TIME'
        WHEN DATEDIFF(MINUTE, o.ORDER_DATE, fd.DELIVERY_DATE) <=
            TRY_CAST(REGEXP_REPLACE(fd.ESTIMATED_TIME, '[^0-9]', '') AS INTEGER) + 10
        THEN 'SLIGHTLY_DELAYED'
        WHEN DATEDIFF(MINUTE, o.ORDER_DATE, fd.DELIVERY_DATE) <=
            TRY_CAST(REGEXP_REPLACE(fd.ESTIMATED_TIME, '[^0-9]', '') AS INTEGER) + 20
        THEN 'DELAYED'
        ELSE 'SEVERELY_DELAYED'
    END AS DELIVERY_TIMELINESS,

    CASE
        WHEN DATEDIFF(MINUTE, o.ORDER_DATE, fd.DELIVERY_DATE) <= 30 THEN 'FAST'
        WHEN DATEDIFF(MINUTE, o.ORDER_DATE, fd.DELIVERY_DATE) <= 45 THEN 'NORMAL'
        WHEN DATEDIFF(MINUTE, o.ORDER_DATE, fd.DELIVERY_DATE) <= 60 THEN 'SLOW'
        ELSE 'VERY_SLOW'
    END AS DELIVERY_SPEED,

    -- Distance Proxy (same city/locality indicator)
    CASE
        WHEN ca.LOCALITY = r.LOCALITY THEN 'SAME_LOCALITY'
        WHEN ca.CITY = l.CITY THEN 'SAME_CITY'
        ELSE 'DIFFERENT_CITY'
    END AS DELIVERY_DISTANCE_CATEGORY,

    -- Success Flags
    CASE
        WHEN o.CURRENT_STATUS = 'COMPLETED'
            AND fd.CURRENT_STATUS = 'DELIVERED'
        THEN 1
        ELSE 0
    END AS IS_SUCCESSFULLY_FULFILLED,

    CASE
        WHEN o.CURRENT_STATUS = 'CANCELLED'
            OR fd.CURRENT_STATUS = 'FAILED'
        THEN 1
        ELSE 0
    END AS IS_FAILED_FULFILLMENT,

    -- Time of Day
    HOUR(o.ORDER_DATE) AS ORDER_HOUR,
    CASE
        WHEN HOUR(o.ORDER_DATE) BETWEEN 6 AND 11 THEN 'MORNING'
        WHEN HOUR(o.ORDER_DATE) BETWEEN 12 AND 16 THEN 'AFTERNOON'
        WHEN HOUR(o.ORDER_DATE) BETWEEN 17 AND 21 THEN 'EVENING'
        ELSE 'NIGHT'
    END AS TIME_OF_DAY,

    -- Day Context
    d.DAY_NAME,
    CASE
        WHEN d.DAY_OF_WEEK IN (6, 7) THEN 'WEEKEND'
        ELSE 'WEEKDAY'
    END AS DAY_TYPE,

    -- Agent Performance Context
    COUNT(DISTINCT fd.DELIVERY_ID) OVER (
        PARTITION BY fd.DELIVERY_AGENT_ID, DATE(fd.DELIVERY_DATE)
    ) AS AGENT_DELIVERIES_SAME_DAY,

    CURRENT_TIMESTAMP() AS CREATED_AT

FROM {{ ref('fact_order') }} o
LEFT JOIN {{ ref('dim_customer') }} c
    ON o.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN {{ ref('dim_restaurant') }} r
    ON o.RESTAURANT_ID = r.RESTAURANT_ID
LEFT JOIN {{ ref('dim_location') }} l
    ON r.LOCATION_ID = l.LOCATION_ID
LEFT JOIN {{ ref('fact_delivery') }} fd
    ON o.ORDER_ID = fd.ORDER_ID
LEFT JOIN {{ ref('dim_delivery_agent') }} da
    ON fd.DELIVERY_AGENT_ID = da.DELIVERY_AGENT_ID
LEFT JOIN {{ ref('dim_customer_address') }} ca
    ON fd.CUSTOMER_ADDRESS_ID = ca.CUSTOMER_ADDRESS_ID
LEFT JOIN {{ ref('dim_date') }} d
    ON DATE(o.ORDER_DATE) = d.CALENDAR_DATE