-- ====================================================================================================
-- CUSTOMER
-- ====================================================================================================
-- CHANGE CONTEXT
USE DATABASE DATAVELOCITY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;

-- ----------------------------------------------------------------------------------------------------
-- CREATE CUSTOMER_BRZ
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.CUSTOMER_BRZ (
    CUSTOMER_BRZ_ID INTEGER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    MOBILE VARCHAR(20) WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    EMAIL VARCHAR(50) WITH TAG (COMMON.PII_POLICY_TAG = 'EMAIL'),
    LOGIN_BY_USING VARCHAR(20),
    GENDER VARCHAR(10) WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    DOB DATE WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    ANNIVERSARY DATE,
    PREFERENCES VARIANT,

    -- RAW COLUMNS
    NAME_RAW VARCHAR,
    MOBILE_RAW VARCHAR,
    EMAIL_RAW VARCHAR,
    LOGIN_BY_USING_RAW VARCHAR,
    GENDER_RAW VARCHAR,
    DOB_RAW VARCHAR,
    ANNIVERSARY_RAW VARCHAR,
    PREFERENCES_RAW VARCHAR,

    -- AUDIT COLUMNS
    INGEST_RUN_ID INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'CUSTOMER BRONZE TABLE WITH RAW AND TRANSFORMED COLUMNS. RAW COLUMNS STORE AS-IS DATA FROM SOURCE, MAIN COLUMNS CONTAIN TYPE-CONVERTED VALUES (NULL IF CONVERSION FAILS).';
ALTER TABLE BRONZE.CUSTOMER_BRZ CLUSTER BY (INGEST_RUN_ID);

-- CREATING SEQUNCE TO GENERATE INGEST_RUN_ID
CREATE OR REPLACE SEQUENCE SEQ_CUSTOMER_INGEST_RUN_ID START = 1 INCREMENT = 1;

-- ----------------------------------------------------------------------------------------------------
-- CREATE CUSTOMER_LOAD_ERROR
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.CUSTOMER_LOAD_ERROR(
    ERROR_ID INTEGER PRIMARY KEY,
    VALIDATE_COLUMN VARCHAR(50),
    VALIDATION_TYPE VARCHAR(30),
    VALIDATION_ERROR_MSG VARCHAR(200),
    INGEST_RUN_ID INTEGER
);
-- ----------------------------------------------------------------------------------------------------
-- CREATE CUSTOMER_SLV
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.CUSTOMER_SLV (
    CUSTOMER_SLV_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    MOBILE VARCHAR(15)  WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    EMAIL VARCHAR(100) WITH TAG (COMMON.PII_POLICY_TAG = 'EMAIL'),
    LOGIN_BY_USING VARCHAR(50),
    GENDER VARCHAR(10)  WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    DOB DATE WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    ANNIVERSARY DATE,
    PREFERENCES VARCHAR,

    BATCH_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP_TZ(9)
)
COMMENT = 'CUSTOMER ENTITY UNDER CLEAN SCHEMA WITH APPROPRIATE DATA TYPE UNDER CLEAN SCHEMA LAYER, DATA IS POPULATED USING MERGE STATEMENT FROM THE STAGE LAYER LOCATION TABLE. THIS TABLE DOES NOT SUPPORT SCD2';
ALTER TABLE SILVER.CUSTOMER_SLV CLUSTER BY (MOBILE, EMAIL);
-- ----------------------------------------------------------------------------------------------------
-- CREATE CUSTOMER_DIM
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE GOLD.DIM_CUSTOMER (
    CUSTOMER_ID INTEGER PRIMARY KEY AUTOINCREMENT,                                 -- NATURAL KEY FOR THE CUSTOMER
    CUSTOMER_NAME STRING(100) NOT NULL,                                   -- CUSTOMER NAME
    MOBILE STRING(15) WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),                                           -- MOBILE NUMBER
    EMAIL STRING(100) WITH TAG (COMMON.PII_POLICY_TAG = 'EMAIL'),                                           -- EMAIL
    LOGIN_BY_USING STRING(50),                                   -- METHOD OF LOGIN
    GENDER STRING(10) WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),                                           -- GENDER
    DOB DATE WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),                                                    -- DATE OF BIRTH
    ANNIVERSARY DATE,                                            -- ANNIVERSARY
    PREFERENCES STRING,                                          -- PREFERENCES

    -- SCD 2 METADATA
    STATUS VARCHAR DEFAULT 'ACTIVE',
    EFF_START_DT TIMESTAMP_TZ,
    EFF_END_DT TIMESTAMP_TZ,
    BATCH_ID VARCHAR,
    CREATED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'CUSTOMER DIMENSION TABLE WITH SCD TYPE 2 HANDLING FOR HISTORICAL TRACKING.';
ALTER TABLE GOLD.DIM_CUSTOMER CLUSTER BY (CUSTOMER_ID, STATUS, EFF_START_DT);

-- =====================================================