-- ====================================================================================================
-- CUSTOMER_ADDRESS
-- ====================================================================================================
-- CHANGE CONSTRING(100)
USE DATABASE DATAVELOCITY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;
-- ----------------------------------------------------------------------------------------------------
-- CREATE CUSTOMER_ADDRESS
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.CUSTOMER_ADDRESS_BRZ (
    CUSTOMER_ADDRESS_ID INTEGER PRIMARY KEY,
    CUSTOMER_ID INTEGER,
    FLAT_NO INTEGER,
    HOUSE_NO INTEGER,
    FLOOR_NO INTEGER,
    BUILDING VARCHAR(100),
    LANDMARK VARCHAR(100),
    LOCALITY VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    ZIPCODE INTEGER,
    COORDINATES VARCHAR(100),
    PRIMARYFLAG VARCHAR(100),
    ADDRESSTYPE VARCHAR(100),

    -- RAW_COLUMNS
    CUSTOMER_ID_RAW VARCHAR,
    FLAT_NO_RAW VARCHAR,
    HOUSE_NO_RAW VARCHAR,
    FLOOR_NO_RAW VARCHAR,
    BUILDING_RAW VARCHAR,
    LANDMARK_RAW VARCHAR,
    LOCALITY_RAW VARCHAR,
    CITY_RAW VARCHAR,
    STATE_RAW VARCHAR,
    ZIPCODE_RAW VARCHAR,
    COORDINATES_RAW VARCHAR,
    PRIMARYFLAG_RAW VARCHAR,
    ADDRESSTYPE_RAW VARCHAR,

    -- AUDIT COLUMNS
    INGEST_RUN_ID INTEGER,
    CREATED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ
    )
COMMENT = 'THIS IS THE CUSTOMER ADDRESS STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE STRING(100) DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';
ALTER TABLE BRONZE.CUSTOMER_ADDRESS_BRZ CLUSTER BY (STATE);

-- CREATING SEQUNCE TO GENERATE INGEST_RUN_ID
CREATE OR REPLACE SEQUENCE SEQ_CUSTOMER_ADDRESS_INGEST_RUN_ID START = 1 INCREMENT = 1;

-- ----------------------------------------------------------------------------------------------------
-- CREATE CUSTOMER_ADDRESS_LOAD_ERROR
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.CUSTOMER_ADDRESS_LOAD_ERROR(
    ERROR_ID INTEGER PRIMARY KEY,
    VALIDATE_COLUMN VARCHAR(50),
    VALIDATION_TYPE VARCHAR(30),
    VALIDATION_ERROR_MSG VARCHAR(200),
    INGEST_RUN_ID INTEGER
);

-- ----------------------------------------------------------------------------------------------------
-- CREATE CUSTOMER_ADDRESS_SLV
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.CUSTOMER_ADDRESS_SLV (
    CUSTOMER_ADDRESS_ID INTEGER PRIMARY KEY,
    CUSTOMER_ID INTEGER,
    FLAT_NO INTEGER,
    HOUSE_NO INTEGER,
    FLOOR_NO INTEGER,
    BUILDING VARCHAR,
    LANDMARK VARCHAR,
    LOCALITY VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    ZIPCODE INTEGER,
    COORDINATES VARCHAR,
    PRIMARY_FLAG VARCHAR,
    ADDRESS_TYPE VARCHAR,

    -- AUDIT COLUMNS
    BATCH_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ

)
COMMENT = 'CUSTOMER ADDRESS ENTITY UNDER CLEAN SCHEMA WITH APPROPRIATE DATA TYPE UNDER CLEAN SCHEMA LAYER, DATA IS POPULATED USING MERGE STATEMENT FROM THE STAGE LAYER LOCATION TABLE. THIS TABLE DOES NOT SUPPORT SCD2';

-- ----------------------------------------------------------------------------------------------------
-- CREATE DIM_CUSTOMER_ADDRESS
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE GOLD.DIM_CUSTOMER_ADDRESS (
    CUSTOMER_ADDRESS_ID INTEGER PRIMARY KEY,
    CUSTOMER_ID INTEGER,
    FLAT_NO INTEGER,
    HOUSE_NO INTEGER,
    FLOOR_NO INTEGER,
    BUILDING VARCHAR,
    LANDMARK VARCHAR,
    LOCALITY VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    ZIPCODE INTEGER,
    COORDINATES VARCHAR,
    PRIMARY_FLAG VARCHAR,
    ADDRESS_TYPE VARCHAR,

    -- SCD 2 METADATA
    STATUS VARCHAR DEFAULT 'ACTIVE',
    EFF_START_DT TIMESTAMP_TZ,
    EFF_END_DT TIMESTAMP_TZ,
    BATCH_ID VARCHAR,
    CREATED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
