-- ====================================================================================================
-- DELIVERY_AGENT
-- ====================================================================================================
-- CHANGE CONVARCHAR
USE DATABASE DATAVELOCITY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;

-- ----------------------------------------------------------------------------------------------------
-- CREATE DELIVERY_AGENT_BRZ
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.DELIVERY_AGENT_BRZ (
    DELIVERY_AGENT_ID INTEGER PRIMARY KEY,
    DELIVERY_AGENT_NAME VARCHAR,
    PHONE INTEGER,
    VEHICLE_TYPE VARCHAR,
    LOCATION_ID INTEGER,
    IS_ACTIVE VARCHAR,
    GENDER VARCHAR,
    RATING NUMBER(2,1),

    DELIVERY_AGENT_NAME_RAW VARCHAR,
    PHONE_RAW VARCHAR,
    VEHICLE_TYPE_RAW VARCHAR,
    LOCATION_ID_RAW VARCHAR,
    IS_ACTIVE_RAW VARCHAR,
    GENDER_RAW VARCHAR,
    RATING_RAW VARCHAR,

    INGEST_RUN_ID INTEGER,
    CREATED_AT VARCHAR,
    UPDATED_AT VARCHAR
)
COMMENT = 'THIS IS THE DELIVERY STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE VARCHAR DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';
ALTER TABLE BRONZE.DELIVERY_AGENT_BRZ CLUSTER BY (INGEST_RUN_ID);

-- CREATING SEQUNCE TO GENERATE INGEST_RUN_ID
CREATE OR REPLACE SEQUENCE SEQ_DELIVERY_AGENT_INGEST_RUN_ID START = 1 INCREMENT = 1;

-- ----------------------------------------------------------------------------------------------------
-- CREATE DELIVERY_AGENT_LOAD_ERROR
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.DELIVERY_AGENT_LOAD_ERROR(
    ERROR_ID INTEGER PRIMARY KEY,
    VALIDATE_COLUMN VARCHAR(50),
    VALIDATION_TYPE VARCHAR(30),
    VALIDATION_ERROR_MSG VARCHAR(200),
    INGEST_RUN_ID INTEGER
);

-- ----------------------------------------------------------------------------------------------------
-- CREATE DELIVERY_AGENT_SLV
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.DELIVERY_AGENT_SLV (
    DELIVERY_AGENT_ID INTEGER PRIMARY KEY,
    DELIVERY_AGENT_NAME VARCHAR,
    PHONE INTEGER,
    VEHICLE_TYPE VARCHAR,
    LOCATION_ID INT,
    IS_ACTIVE VARCHAR,
    GENDER VARCHAR,
    RATING NUMBER(2,1),

    -- AUDIT COLUMNS
    BATCH_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ
)
COMMENT = 'DELIVERY ENTITY UNDER CLEAN SCHEMA WITH APPROPRIATE DATA TYPE UNDER CLEAN SCHEMA LAYER, DATA IS POPULATED USING MERGE STATEMENT FROM THE STAGE LAYER LOCATION TABLE. THIS TABLE DOES NOT SUPPORT SCD2';

-- ----------------------------------------------------------------------------------------------------
-- CREATE DELIVERY_AGENT_GLD
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE GOLD.DIM_DELIVERY_AGENT (
    DELIVERY_AGENT_ID INTEGER PRIMARY KEY,
    DELIVERY_AGENT_NAME VARCHAR,
    PHONE VARCHAR,
    VEHICLE_TYPE VARCHAR,
    LOCATION_ID INTEGER,
    IS_ACTIVE VARCHAR,
    GENDER VARCHAR,
    RATING NUMBER(2,1),

    -- SCD 2 METADATA
    STATUS VARCHAR DEFAULT 'ACTIVE',
    EFF_START_DT TIMESTAMP_TZ,
    EFF_END_DT TIMESTAMP_TZ,
    BATCH_ID VARCHAR,
    CREATED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT =  'DIM TABLE FOR DELIVERY AGENT ENTITY WITH SCD2 SUPPORT.';