-- ====================================================================================================
-- MENU
-- ====================================================================================================
-- CHANGE CONSTRING
USE DATABASE DATAVELOCITY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;

-- ----------------------------------------------------------------------------------------------------
-- CREATE MENU_BRZ
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.MENU_BRZ (
    MENU_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RESTAURANT_ID INTEGER,
    ITEM_NAME VARCHAR,
    DESCRIPTION VARCHAR,
    PRICE NUMBER(10, 2),
    CATEGORY VARCHAR,
    AVAILABILITY VARCHAR,
    ITEM_TYPE VARCHAR,

    MENU_ID_RAW VARCHAR,
    RESTAURANT_ID_RAW VARCHAR,
    ITEM_NAME_RAW VARCHAR,
    DESCRIPTION_RAW VARCHAR,
    PRICE_RAW VARCHAR,
    CATEGORY_RAW VARCHAR,
    AVAILABILITY_RAW VARCHAR,
    ITEM_TYPE_RAW VARCHAR,

    -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
    INGEST_RUN_ID INTEGER,
    CREATED_AT TIMESTAMP_TZ(9),
    UPDATED_AT TIMESTAMP_TZ(9)
)
COMMENT = 'THIS IS THE MENU STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE STRING DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';
ALTER TABLE BRONZE.MENU_BRZ CLUSTER BY (INGEST_RUN_ID);

-- CREATING SEQUNCE TO GENERATE INGEST_RUN_ID
CREATE OR REPLACE SEQUENCE SEQ_MENU_INGEST_RUN_ID START = 1 INCREMENT = 1;

-- ----------------------------------------------------------------------------------------------------
-- CREATE MENU_LOAD_ERROR
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.MENU_LOAD_ERROR(
    ERROR_ID INTEGER PRIMARY KEY,
    VALIDATE_COLUMN VARCHAR(50),
    VALIDATION_TYPE VARCHAR(30),
    VALIDATION_ERROR_MSG VARCHAR(200),
    INGEST_RUN_ID INTEGER
);

-- ----------------------------------------------------------------------------------------------------
-- CREATE MENU_SLV
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.MENU_SLV (
    MENU_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RESTAURANT_ID INTEGER,
    ITEM_NAME VARCHAR,
    DESCRIPTION VARCHAR,
    PRICE DECIMAL(10, 2),
    CATEGORY VARCHAR,
    AVAILABILITY BOOLEAN,
    ITEM_TYPE VARCHAR,

    CREATED_AT TIMESTAMP_TZ(9),
    UPDATED_AT TIMESTAMP_TZ(9),
    BATCH_ID VARCHAR(36)
)
COMMENT = 'MENU ENTITY UNDER CLEAN SCHEMA WITH APPROPRIATE DATA TYPE UNDER CLEAN SCHEMA LAYER, DATA IS POPULATED USING MERGE STATEMENT FROM THE STAGE LAYER LOCATION TABLE. THIS TABLE DOES NOT SUPPORT SCD2';

-- ----------------------------------------------------------------------------------------------------
-- CREATE DIM_MENU
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE GOLD.DIM_MENU (
    MENU_ID INTEGER PRIMARY KEY,
    RESTAURANT_ID INTEGER,
    ITEM_NAME STRING,
    DESCRIPTION STRING,
    PRICE DECIMAL(10, 2),
    CATEGORY STRING,
    AVAILABILITY BOOLEAN,
    ITEM_TYPE STRING,

    -- SCD 2 METADATA
    STATUS VARCHAR DEFAULT 'ACTIVE',
    EFF_START_DT TIMESTAMP_TZ,
    EFF_END_DT TIMESTAMP_TZ,
    BATCH_ID VARCHAR,
    CREATED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'THIS TABLE STORES THE DIMENSION DATA FOR THE MENU ITEMS, TRACKING HISTORICAL CHANGES USING SCD TYPE 2. EACH MENU ITEM HAS AN EFFECTIVE START AND END DATE, WITH A FLAG INDICATING IF IT IS THE CURRENT RECORD OR HISTORICAL. THE HASH KEY (MENU_DIM_HK) IS GENERATED BASED ON MENU_ID AND RESTAURANT_ID.';
-- ====================================================================================================