-- ====================================================================================================
-- RESTAURANT
-- ====================================================================================================
-- CHANGE CONTEXT
USE ROLE ACCOUNTADMIN;
USE DATABASE DATAVELOCITY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;

-- ----------------------------------------------------------------------------------------------------
-- CREATE RESTAURANT_BRZ
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.RESTAURANT_BRZ (
    RESTAURANT_ID INTEGER PRIMARY KEY,
    FSSAI_REGISTRATION_NO INTEGER,
    RESTAURANT_NAME VARCHAR ,
    CUISINE_TYPE VARCHAR,
    PRICING_FOR_TWO NUMBER(10,2),
    RESTAURANT_PHONE VARCHAR WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),
    OPERATING_HOURS VARCHAR,
    LOCATION_ID INTEGER,
    ACTIVE_FLAG VARCHAR,
    OPEN_STATUS VARCHAR,
    LOCALITY VARCHAR,
    RESTAURANT_ADDRESS VARCHAR,
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6),

    -- RAW COLUMNS
    RESTAURANT_ID_RAW INTEGER,
    FSSAI_REGISTRATION_NO_RAW VARCHAR,
    RESTAURANT_NAME_RAW VARCHAR,
    CUISINE_TYPE_RAW VARCHAR,
    PRICING_FOR_TWO_RAW VARCHAR,
    RESTAURANT_PHONE_RAW VARCHAR WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),
    OPERATING_HOURS_RAW VARCHAR,
    LOCATION_ID_RAW VARCHAR,
    ACTIVE_FLAG_RAW VARCHAR,
    OPEN_STATUS_RAW VARCHAR,
    LOCALITY_RAW VARCHAR,
    RESTAURANT_ADDRESS_RAW VARCHAR,
    LATITUDE_RAW VARCHAR,
    LONGITUDE_RAW VARCHAR,

    -- AUDIT COLUMNS
    INGEST_RUN_ID INTEGER,
    CREATED_AT STRING,
    UPDATED_AT STRING
)
COMMENT = 'THIS IS THE RESTAURANT STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE TEXT DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';
ALTER TABLE BRONZE.LOCATION_BRZ CLUSTER BY (INGEST_RUN_ID);

-- CREATING SEQUNCE TO GENERATE INGEST_RUN_ID
CREATE OR REPLACE SEQUENCE SEQ_RESTAURANT_INGEST_RUN_ID START = 1 INCREMENT = 1;
-- ----------------------------------------------------------------------------------------------------
-- CREATE RESTAURANT_LOAD_ERROR
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.RESTAURANT_LOAD_ERROR(
    ERROR_ID INTEGER PRIMARY KEY,
    VALIDATE_COLUMN VARCHAR(50),
    VALIDATION_TYPE VARCHAR(30),
    VALIDATION_ERROR_MSG VARCHAR(200),
    INGEST_RUN_ID INTEGER
);
-- ----------------------------------------------------------------------------------------------------
-- CREATE RESTAURANT_SLV
-- ----------------------------------------------------------------------------------------------------
select * from silver.restaurant_slv;

CREATE OR REPLACE TABLE SILVER.RESTAURANT_SLV (
    RESTAURANT_ID INTEGER PRIMARY KEY,
    FSSAI_REGISTRATION_NO INTEGER,
    RESTAURANT_NAME VARCHAR(100),
    CUISINE_TYPE VARCHAR,
    PRICING_FOR_TWO NUMBER(10, 2),
    RESTAURANT_PHONE STRING(15) WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),
    OPERATING_HOURS VARCHAR(100),
    LOCATION_ID VARCHAR,
    ACTIVE_FLAG VARCHAR(10),
    OPEN_STATUS VARCHAR(30),
    LOCALITY VARCHAR(100),
    RESTAURANT_ADDRESS VARCHAR,
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6),

    BATCH_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ
)
COMMENT = 'RESTAURANT ENTITY UNDER CLEAN SCHEMA WITH APPROPRIATE DATA TYPE UNDER CLEAN SCHEMA LAYER, DATA IS POPULATED USING MERGE STATEMENT FROM THE STAGE LAYER LOCATION TABLE. THIS TABLE DOES NOT SUPPORT SCD2';

-- ----------------------------------------------------------------------------------------------------
-- CREATE RESTAURANT
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE GOLD.DIM_RESTAURANT (
    RESTAURANT_ID INTEGER PRIMARY KEY,
    FSSAI_REGISTRATION_NO INTEGER,
    RESTAURANT_NAME VARCHAR(100),
    CUISINE_TYPE VARCHAR,
    PRICING_FOR_TWO NUMBER(10, 2),
    RESTAURANT_PHONE VARCHAR(15) WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),
    OPERATING_HOURS VARCHAR(100),
    LOCATION_ID NUMBER,
    ACTIVE_FLAG VARCHAR(10),
    OPEN_STATUS VARCHAR(30),
    LOCALITY VARCHAR(100),
    RESTAURANT_ADDRESS VARCHAR,
    LATITUDE NUMBER(9, 6),
    LONGITUDE NUMBER(9, 6),

    -- SCD 2 METADATA
    STATUS VARCHAR DEFAULT 'ACTIVE',
    EFF_START_DT TIMESTAMP_TZ,
    EFF_END_DT TIMESTAMP_TZ,
    BATCH_ID VARCHAR,
    CREATED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'DIMENSIONAL TABLE FOR RESTAURANT ENTITY WITH HASH KEYS AND SCD ENABLED.';
-- =====================================================