-- ====================================================================================================
-- CUSTOMER_ADDRESS
-- ====================================================================================================
-- CHANGE CONTEXT
USE DATABASE SWIGGY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;
-- ----------------------------------------------------------------------------------------------------
-- CREATE CUSTOMER_ADDRESS
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.CUSTOMER_ADDRESS_BRZ (
    ADDRESSID TEXT,                    -- PRIMARY KEY AS TEXT
    CUSTOMER_ID TEXT COMMENT 'CUSTOMER FK (SOURCE DATA)',                   -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
    FLATNO TEXT,                       -- FLAT NUMBER AS TEXT
    HOUSENO TEXT,                      -- HOUSE NUMBER AS TEXT
    FLOOR TEXT,                        -- FLOOR AS TEXT
    BUILDING TEXT,                     -- BUILDING NAME AS TEXT
    LANDMARK TEXT,                     -- LANDMARK AS TEXT
    LOCALITY TEXT,                     -- LOCALITY AS TEXT
    CITY TEXT,                          -- CITY AS TEXT
    STATE TEXT,                         -- STATE AS TEXT
    PINCODE TEXT,                       -- PINCODE AS TEXT
    COORDINATES TEXT,                  -- COORDINATES AS TEXT
    PRIMARYFLAG TEXT,                  -- PRIMARY FLAG AS TEXT
    ADDRESSTYPE TEXT,                  -- ADDRESS TYPE AS TEXT
    CREATEDDATE TEXT,                  -- CREATED DATE AS TEXT
    MODIFIEDDATE TEXT,                 -- MODIFIED DATE AS TEXT
    -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
    STG_FILE_NAME TEXT,
    STG_FILE_LOAD_TS TIMESTAMP,
    STG_FILE_MD5 TEXT,
    COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
COMMENT = 'THIS IS THE CUSTOMER ADDRESS STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE TEXT DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';

-- ----------------------------------------------------------------------------------------------------
-- CREATE CUSTOMER_ADDRESS_SLV
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.CUSTOMER_ADDRESS_SLV (
    CUSTOMER_ADDRESS_SK NUMBER AUTOINCREMENT PRIMARY KEY COMMENT 'SURROGATE KEY (EWH)',                -- AUTO-INCREMENTED PRIMARY KEY
    ADDRESS_ID INT COMMENT 'PRIMARY KEY (SOURCE DATA)',                 -- PRIMARY KEY AS STRING
    CUSTOMER_ID_FK INT COMMENT 'CUSTOMER FK (SOURCE DATA)',                -- FOREIGN KEY REFERENCE AS STRING (NO CONSTRAINT IN SNOWFLAKE)
    FLAT_NO STRING,                    -- FLAT NUMBER AS STRING
    HOUSE_NO STRING,                   -- HOUSE NUMBER AS STRING
    FLOOR STRING,                      -- FLOOR AS STRING
    BUILDING STRING,                   -- BUILDING NAME AS STRING
    LANDMARK STRING,                   -- LANDMARK AS STRING
    LOCALITY STRING,                   -- LOCALITY AS STRING
    CITY STRING,                       -- CITY AS STRING
    STATE STRING,                      -- STATE AS STRING
    PINCODE STRING,                    -- PINCODE AS STRING
    COORDINATES STRING,                -- COORDINATES AS STRING
    PRIMARY_FLAG STRING,               -- PRIMARY FLAG AS STRING
    ADDRESS_TYPE STRING,               -- ADDRESS TYPE AS STRING
    CREATED_DATE TIMESTAMP_TZ,         -- CREATED DATE AS TIMESTAMP WITH TIME ZONE
    MODIFIED_DATE TIMESTAMP_TZ,        -- MODIFIED DATE AS TIMESTAMP WITH TIME ZONE
    -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
    STG_FILE_NAME STRING,
    STG_FILE_LOAD_TS TIMESTAMP,
    STG_FILE_MD5 STRING,
    COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
COMMENT = 'CUSTOMER ADDRESS ENTITY UNDER CLEAN SCHEMA WITH APPROPRIATE DATA TYPE UNDER CLEAN SCHEMA LAYER, DATA IS POPULATED USING MERGE STATEMENT FROM THE STAGE LAYER LOCATION TABLE. THIS TABLE DOES NOT SUPPORT SCD2';

-- ----------------------------------------------------------------------------------------------------
-- CREATE DIM_CUSTOMER_ADDRESS
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE GOLD.DIM_CUSTOMER_ADDRESS (
    CUSTOMER_ADDRESS_HK NUMBER PRIMARY KEY COMMENT 'CUSTOMER ADDRESS HK (EDW)',        -- SURROGATE KEY (HASH KEY)
    ADDRESS_ID INT COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',                                -- ORIGINAL PRIMARY KEY
    CUSTOMER_ID_FK STRING COMMENT 'CUSTOMER FK (SOURCE SYSTEM)',                            -- SURROGATE KEY FROM CUSTOMER DIMENSION (FOREIGN KEY)
    FLAT_NO STRING,                                -- FLAT NUMBER
    HOUSE_NO STRING,                               -- HOUSE NUMBER
    FLOOR STRING,                                  -- FLOOR
    BUILDING STRING,                               -- BUILDING NAME
    LANDMARK STRING,                               -- LANDMARK
    LOCALITY STRING,                               -- LOCALITY
    CITY STRING,                                   -- CITY
    STATE STRING,                                  -- STATE
    PINCODE STRING,                                -- PINCODE
    COORDINATES STRING,                            -- GEO-COORDINATES
    PRIMARY_FLAG STRING,                           -- WHETHER IT'S THE PRIMARY ADDRESS
    ADDRESS_TYPE STRING,                           -- TYPE OF ADDRESS (E.G., HOME, OFFICE)

    -- SCD2 COLUMNS
    EFF_START_DATE TIMESTAMP_TZ,                                 -- EFFECTIVE START DATE
    EFF_END_DATE TIMESTAMP_TZ,                                   -- EFFECTIVE END DATE (NULL IF ACTIVE)
    IS_CURRENT BOOLEAN                                           -- FLAG TO INDICATE THE CURRENT RECORD
);


-- ----------------------------------------------------------------------------------------------------
-- CREATE STAGE TO BRONZE
-- ----------------------------------------------------------------------------------------------------
COPY INTO BRONZE.CUSTOMER_ADDRESS_BRZ (ADDRESSID, CUSTOMER_ID, FLATNO, HOUSENO, FLOOR, BUILDING,
                               LANDMARK, LOCALITY,CITY,PINCODE, STATE, COORDINATES, PRIMARYFLAG, ADDRESSTYPE,
                               CREATEDDATE, MODIFIEDDATE,
                               STG_FILE_NAME, STG_FILE_LOAD_TS, STG_FILE_MD5, COPY_DATA_TS)
FROM (
    SELECT
        T.$1::TEXT AS ADDRESSID,
        T.$2::TEXT AS CUSTOMER_ID,
        T.$3::TEXT AS FLATNO,
        T.$4::TEXT AS HOUSENO,
        T.$5::TEXT AS FLOOR,
        T.$6::TEXT AS BUILDING,
        T.$7::TEXT AS LANDMARK,
        T.$8::TEXT AS LOCALITY,
        T.$9::TEXT AS CITY,
        T.$10::TEXT AS STATE,
        T.$11::TEXT AS PINCODE,
        T.$12::TEXT AS COORDINATES,
        T.$13::TEXT AS PRIMARYFLAG,
        T.$14::TEXT AS ADDRESSTYPE,
        T.$15::TEXT AS CREATEDDATE,
        T.$16::TEXT AS MODIFIEDDATE,
        METADATA$FILENAME AS _STG_FILE_NAME,
        METADATA$FILE_LAST_MODIFIED AS _STG_FILE_LOAD_TS,
        METADATA$FILE_CONTENT_KEY AS _STG_FILE_MD5,
        CURRENT_TIMESTAMP AS _COPY_DATA_TS
    FROM '@"SWIGGY"."BRONZE"."CSV_STG"/customer_address/customer_address_book_initial.csv' T
)
FILE_FORMAT = (FORMAT_NAME = 'BRONZE.CSV_FILE_FORMAT')
ON_ERROR = ABORT_STATEMENT;

-- ----------------------------------------------------------------------------------------------------
-- CREATE BRONZE TO SILVER
-- ----------------------------------------------------------------------------------------------------
MERGE INTO SILVER.CUSTOMER_ADDRESS_SLV AS CLEAN
USING (
    SELECT
        CAST(ADDRESSID AS INT) AS ADDRESS_ID,
        CAST(CUSTOMER_ID AS INT) AS CUSTOMER_ID_FK,
        FLATNO AS FLAT_NO,
        HOUSENO AS HOUSE_NO,
        FLOOR,
        BUILDING,
        LANDMARK,
        LOCALITY,
        CITY,
        STATE,
        PINCODE,
        COORDINATES,
        PRIMARYFLAG AS PRIMARY_FLAG,
        ADDRESSTYPE AS ADDRESS_TYPE,
        TRY_TO_TIMESTAMP_TZ(CREATEDDATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS CREATED_DATE,
        TRY_TO_TIMESTAMP_TZ(MODIFIEDDATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS MODIFIED_DATE,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    FROM BRONZE.CUSTOMER_ADDRESS_BRZ
) AS STAGE
ON CLEAN.ADDRESS_ID = STAGE.ADDRESS_ID
-- INSERT NEW RECORDS
WHEN NOT MATCHED THEN
    INSERT (
        ADDRESS_ID,
        CUSTOMER_ID_FK,
        FLAT_NO,
        HOUSE_NO,
        FLOOR,
        BUILDING,
        LANDMARK,
        LOCALITY,
        CITY,
        STATE,
        PINCODE,
        COORDINATES,
        PRIMARY_FLAG,
        ADDRESS_TYPE,
        CREATED_DATE,
        MODIFIED_DATE,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    )
    VALUES (
        STAGE.ADDRESS_ID,
        STAGE.CUSTOMER_ID_FK,
        STAGE.FLAT_NO,
        STAGE.HOUSE_NO,
        STAGE.FLOOR,
        STAGE.BUILDING,
        STAGE.LANDMARK,
        STAGE.LOCALITY,
        STAGE.CITY,
        STAGE.STATE,
        STAGE.PINCODE,
        STAGE.COORDINATES,
        STAGE.PRIMARY_FLAG,
        STAGE.ADDRESS_TYPE,
        STAGE.CREATED_DATE,
        STAGE.MODIFIED_DATE,
        STAGE.STG_FILE_NAME,
        STAGE.STG_FILE_LOAD_TS,
        STAGE.STG_FILE_MD5,
        STAGE.COPY_DATA_TS
    )
-- UPDATE EXISTING RECORDS
WHEN MATCHED THEN
    UPDATE SET
        CLEAN.FLAT_NO = STAGE.FLAT_NO,
        CLEAN.HOUSE_NO = STAGE.HOUSE_NO,
        CLEAN.FLOOR = STAGE.FLOOR,
        CLEAN.BUILDING = STAGE.BUILDING,
        CLEAN.LANDMARK = STAGE.LANDMARK,
        CLEAN.LOCALITY = STAGE.LOCALITY,
        CLEAN.CITY = STAGE.CITY,
        CLEAN.STATE = STAGE.STATE,
        CLEAN.PINCODE = STAGE.PINCODE,
        CLEAN.COORDINATES = STAGE.COORDINATES,
        CLEAN.PRIMARY_FLAG = STAGE.PRIMARY_FLAG,
        CLEAN.ADDRESS_TYPE = STAGE.ADDRESS_TYPE,
        CLEAN.CREATED_DATE = STAGE.CREATED_DATE,
        CLEAN.MODIFIED_DATE = STAGE.MODIFIED_DATE,
        CLEAN.STG_FILE_NAME = STAGE.STG_FILE_NAME,
        CLEAN.STG_FILE_LOAD_TS = STAGE.STG_FILE_LOAD_TS,
        CLEAN.STG_FILE_MD5 = STAGE.STG_FILE_MD5,
        CLEAN.COPY_DATA_TS = STAGE.COPY_DATA_TS;

-- ----------------------------------------------------------------------------------------------------
-- SILVER TO GOLD
-- ----------------------------------------------------------------------------------------------------
MERGE INTO
    GOLD.DIM_CUSTOMER_ADDRESS AS TARGET
USING
    SILVER.CUSTOMER_ADDRESS_SLV AS SOURCE
ON
    TARGET.ADDRESS_ID = SOURCE.ADDRESS_ID AND
    TARGET.CUSTOMER_ID_FK = SOURCE.CUSTOMER_ID_FK AND
    TARGET.FLAT_NO = SOURCE.FLAT_NO AND
    TARGET.HOUSE_NO = SOURCE.HOUSE_NO AND
    TARGET.FLOOR = SOURCE.FLOOR AND
    TARGET.BUILDING = SOURCE.BUILDING AND
    TARGET.LANDMARK = SOURCE.LANDMARK AND
    TARGET.LOCALITY = SOURCE.LOCALITY AND
    TARGET.CITY = SOURCE.CITY AND
    TARGET.STATE = SOURCE.STATE AND
    TARGET.PINCODE = SOURCE.PINCODE AND
    TARGET.COORDINATES = SOURCE.COORDINATES AND
    TARGET.PRIMARY_FLAG = SOURCE.PRIMARY_FLAG AND
    TARGET.ADDRESS_TYPE = SOURCE.ADDRESS_TYPE
WHEN MATCHED
    AND SOURCE.METADATA$ACTION = 'DELETE' AND SOURCE.METADATA$ISUPDATE = 'TRUE' THEN
    -- UPDATE THE EXISTING RECORD TO CLOSE ITS VALIDITY PERIOD
    UPDATE SET
        TARGET.EFF_END_DATE = CURRENT_TIMESTAMP(),
        TARGET.IS_CURRENT = FALSE
WHEN NOT MATCHED
    AND SOURCE.METADATA$ACTION = 'INSERT' AND SOURCE.METADATA$ISUPDATE = 'TRUE' THEN
    -- INSERT NEW RECORD WITH CURRENT DATA AND NEW EFFECTIVE START DATE
    INSERT (
        CUSTOMER_ADDRESS_HK,
        ADDRESS_ID,
        CUSTOMER_ID_FK,
        FLAT_NO,
        HOUSE_NO,
        FLOOR,
        BUILDING,
        LANDMARK,
        LOCALITY,
        CITY,
        STATE,
        PINCODE,
        COORDINATES,
        PRIMARY_FLAG,
        ADDRESS_TYPE,
        EFF_START_DATE,
        EFF_END_DATE,
        IS_CURRENT
    )
    VALUES (
        HASH(SHA1_HEX(CONCAT(SOURCE.ADDRESS_ID, SOURCE.CUSTOMER_ID_FK, SOURCE.FLAT_NO,
            SOURCE.HOUSE_NO, SOURCE.FLOOR, SOURCE.BUILDING, SOURCE.LANDMARK,
            SOURCE.LOCALITY, SOURCE.CITY, SOURCE.STATE, SOURCE.PINCODE,
            SOURCE.COORDINATES, SOURCE.PRIMARY_FLAG, SOURCE.ADDRESS_TYPE))),
        SOURCE.ADDRESS_ID,
        SOURCE.CUSTOMER_ID_FK,
        SOURCE.FLAT_NO,
        SOURCE.HOUSE_NO,
        SOURCE.FLOOR,
        SOURCE.BUILDING,
        SOURCE.LANDMARK,
        SOURCE.LOCALITY,
        SOURCE.CITY,
        SOURCE.STATE,
        SOURCE.PINCODE,
        SOURCE.COORDINATES,
        SOURCE.PRIMARY_FLAG,
        SOURCE.ADDRESS_TYPE,
        CURRENT_TIMESTAMP(),
        NULL,
        TRUE
    )
WHEN NOT MATCHED
    AND SOURCE.METADATA$ACTION = 'INSERT' AND SOURCE.METADATA$ISUPDATE = 'FALSE' THEN
    -- INSERT NEW RECORD WITH CURRENT DATA AND NEW EFFECTIVE START DATE
    INSERT (
        CUSTOMER_ADDRESS_HK,
        ADDRESS_ID,
        CUSTOMER_ID_FK,
        FLAT_NO,
        HOUSE_NO,
        FLOOR,
        BUILDING,
        LANDMARK,
        LOCALITY,
        CITY,
        STATE,
        PINCODE,
        COORDINATES,
        PRIMARY_FLAG,
        ADDRESS_TYPE,
        EFF_START_DATE,
        EFF_END_DATE,
        IS_CURRENT
    )
    VALUES (
        HASH(SHA1_HEX(CONCAT(SOURCE.ADDRESS_ID, SOURCE.CUSTOMER_ID_FK, SOURCE.FLAT_NO,
            SOURCE.HOUSE_NO, SOURCE.FLOOR, SOURCE.BUILDING, SOURCE.LANDMARK,
            SOURCE.LOCALITY, SOURCE.CITY, SOURCE.STATE, SOURCE.PINCODE,
            SOURCE.COORDINATES, SOURCE.PRIMARY_FLAG, SOURCE.ADDRESS_TYPE))),
        SOURCE.ADDRESS_ID,
        SOURCE.CUSTOMER_ID_FK,
        SOURCE.FLAT_NO,
        SOURCE.HOUSE_NO,
        SOURCE.FLOOR,
        SOURCE.BUILDING,
        SOURCE.LANDMARK,
        SOURCE.LOCALITY,
        SOURCE.CITY,
        SOURCE.STATE,
        SOURCE.PINCODE,
        SOURCE.COORDINATES,
        SOURCE.PRIMARY_FLAG,
        SOURCE.ADDRESS_TYPE,
        CURRENT_TIMESTAMP(),
        NULL,
        TRUE
    );
-- ====================================================================================================