-- ====================================================================================================
-- DELIVERY
-- ====================================================================================================
-- CHANGE CONTEXT
USE DATABASE SWIGGY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;

-- ----------------------------------------------------------------------------------------------------
-- CREATE DELIVERY_BRZ
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.DELIVERY_BRZ (
    DELIVERY_ID TEXT COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',                           -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
    ORDERID TEXT COMMENT 'ORDER FK (SOURCE SYSTEM)',                           -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
    DELIVERYAGENTID TEXT COMMENT 'DELIVERY AGENT FK(SOURCE SYSTEM)',                   -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
    DELIVERYSTATUS TEXT,                    -- DELIVERY STATUS AS TEXT
    ESTIMATEDTIME TEXT,                     -- ESTIMATED TIME AS TEXT
    ADDRESSID TEXT COMMENT 'CUSTOMER ADDRESS FK(SOURCE SYSTEM)',                         -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
    DELIVERYDATE TEXT,                      -- DELIVERY DATE AS TEXT
    CREATEDDATE TEXT,                       -- CREATED DATE AS TEXT
    MODIFIEDDATE TEXT,                      -- MODIFIED DATE AS TEXT
    -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
    STG_FILE_NAME TEXT,
    STG_FILE_LOAD_TS TIMESTAMP,
    STG_FILE_MD5 TEXT,
    COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
COMMENT = 'THIS IS THE DELIVERY STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE TEXT DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';

-- ----------------------------------------------------------------------------------------------------
-- CREATE DELIVERY_SLV
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.DELIVERY_SLV (
    DELIVERY_SK INT AUTOINCREMENT PRIMARY KEY COMMENT 'SURROGATE KEY (EDW)', -- PRIMARY KEY WITH AUTO-INCREMENT
    DELIVERY_ID INT NOT NULL COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',
    ORDER_ID_FK NUMBER NOT NULL COMMENT 'ORDER FK (SOURCE SYSTEM)',                        -- FOREIGN KEY REFERENCE, CONVERTED TO NUMERIC TYPE
    DELIVERY_AGENT_ID_FK NUMBER NOT NULL COMMENT 'DELIVERY AGENT FK (SOURCE SYSTEM)',               -- FOREIGN KEY REFERENCE, CONVERTED TO NUMERIC TYPE
    DELIVERY_STATUS STRING,                 -- DELIVERY STATUS, STORED AS A STRING
    ESTIMATED_TIME STRING,                  -- ESTIMATED TIME, STORED AS A STRING
    CUSTOMER_ADDRESS_ID_FK NUMBER NOT NULL  COMMENT 'CUSTOMER ADDRESS FK (SOURCE SYSTEM)',                      -- FOREIGN KEY REFERENCE, CONVERTED TO NUMERIC TYPE
    DELIVERY_DATE TIMESTAMP,                -- DELIVERY DATE, CONVERTED TO TIMESTAMP
    CREATED_DATE TIMESTAMP,                 -- CREATED DATE, CONVERTED TO TIMESTAMP
    MODIFIED_DATE TIMESTAMP,                -- MODIFIED DATE, CONVERTED TO TIMESTAMP

    -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
    STG_FILE_NAME STRING,                  -- SOURCE FILE NAME
    STG_FILE_LOAD_TS TIMESTAMP,            -- SOURCE FILE LOAD TIMESTAMP
    STG_FILE_MD5 STRING,                   -- MD5 CHECKSUM OF THE SOURCE FILE
    COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- METADATA TIMESTAMP
)
COMMENT = 'DELIVERY ENTITY UNDER CLEAN SCHEMA WITH APPROPRIATE DATA TYPE UNDER CLEAN SCHEMA LAYER, DATA IS POPULATED USING MERGE STATEMENT FROM THE STAGE LAYER LOCATION TABLE. THIS TABLE DOES NOT SUPPORT SCD2';

-- ----------------------------------------------------------------------------------------------------
-- CREATE DIM_DELIVERY
-- ----------------------------------------------------------------------------------------------------

-- ----------------------------------------------------------------------------------------------------
-- STAGE TO BRONZE
-- ----------------------------------------------------------------------------------------------------
COPY INTO BRONZE.DELIVERY_BRZ (DELIVERY_ID,ORDERID, DELIVERYAGENTID, DELIVERYSTATUS,
                    ESTIMATEDTIME, ADDRESSID, DELIVERYDATE, CREATEDDATE,
                    MODIFIEDDATE, STG_FILE_NAME, STG_FILE_LOAD_TS,
                    STG_FILE_MD5, COPY_DATA_TS)
FROM (
    SELECT
        T.$1::TEXT AS DELIVERY_ID,
        T.$2::TEXT AS ORDERID,
        T.$3::TEXT AS DELIVERYAGENTID,
        T.$4::TEXT AS DELIVERYSTATUS,
        T.$5::TEXT AS ESTIMATEDTIME,
        T.$6::TEXT AS ADDRESSID,
        T.$7::TEXT AS DELIVERYDATE,
        T.$8::TEXT AS CREATEDDATE,
        T.$9::TEXT AS MODIFIEDDATE,
        METADATA$FILENAME AS STG_FILE_NAME,
        METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
        METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
        CURRENT_TIMESTAMP AS COPY_DATA_TS
    FROM '@"SWIGGY"."BRONZE"."CSV_STG"/delivery/delivery-initial-load.csv' T
)
FILE_FORMAT = (FORMAT_NAME = 'BRONZE.CSV_FILE_FORMAT')
ON_ERROR = ABORT_STATEMENT;

-- ----------------------------------------------------------------------------------------------------
-- BRONZE TO SILVER
-- ----------------------------------------------------------------------------------------------------
MERGE INTO
    SILVER.DELIVERY_SLV AS TARGET
USING
    BRONZE.DELIVERY_BRZ AS SOURCE
ON
    TARGET.DELIVERY_ID = TO_NUMBER(SOURCE.DELIVERY_ID) AND
    TARGET.ORDER_ID_FK = TO_NUMBER(SOURCE.ORDERID) AND
    TARGET.DELIVERY_AGENT_ID_FK = TO_NUMBER(SOURCE.DELIVERYAGENTID)
WHEN MATCHED THEN
    -- UPDATE THE EXISTING RECORD WITH THE LATEST DATA
    UPDATE SET
        DELIVERY_STATUS = SOURCE.DELIVERYSTATUS,
        ESTIMATED_TIME = SOURCE.ESTIMATEDTIME,
        CUSTOMER_ADDRESS_ID_FK = TO_NUMBER(SOURCE.ADDRESSID),
        DELIVERY_DATE = TO_TIMESTAMP(SOURCE.DELIVERYDATE),
        CREATED_DATE = TO_TIMESTAMP(SOURCE.CREATEDDATE),
        MODIFIED_DATE = TO_TIMESTAMP(SOURCE.MODIFIEDDATE),
        STG_FILE_NAME = SOURCE.STG_FILE_NAME,
        STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
        STG_FILE_MD5 = SOURCE.STG_FILE_MD5,
        COPY_DATA_TS = SOURCE.COPY_DATA_TS
WHEN NOT MATCHED THEN
    -- INSERT NEW RECORD IF NO MATCH IS FOUND
    INSERT (
        DELIVERY_ID,
        ORDER_ID_FK,
        DELIVERY_AGENT_ID_FK,
        DELIVERY_STATUS,
        ESTIMATED_TIME,
        CUSTOMER_ADDRESS_ID_FK,
        DELIVERY_DATE,
        CREATED_DATE,
        MODIFIED_DATE,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    )
    VALUES (
        TO_NUMBER(SOURCE.DELIVERY_ID),
        TO_NUMBER(SOURCE.ORDERID),
        TO_NUMBER(SOURCE.DELIVERYAGENTID),
        SOURCE.DELIVERYSTATUS,
        SOURCE.ESTIMATEDTIME,
        TO_NUMBER(SOURCE.ADDRESSID),
        TO_TIMESTAMP(SOURCE.DELIVERYDATE),
        TO_TIMESTAMP(SOURCE.CREATEDDATE),
        TO_TIMESTAMP(SOURCE.MODIFIEDDATE),
        SOURCE.STG_FILE_NAME,
        SOURCE.STG_FILE_LOAD_TS,
        SOURCE.STG_FILE_MD5,
        SOURCE.COPY_DATA_TS
    );

-- ----------------------------------------------------------------------------------------------------
-- SILVER TO GOLD
-- ----------------------------------------------------------------------------------------------------
-- ====================================================================================================