-- ====================================================================================================
-- DELIVERY_AGENT
-- ====================================================================================================
-- CHANGE CONTEXT
USE DATABASE SWIGGY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;

-- ----------------------------------------------------------------------------------------------------
-- CREATE DELIVERY_AGENT_BRZ
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.DELIVERY_AGENT_BRZ (
    DELIVERY_AGENT_ID TEXT COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',         -- PRIMARY KEY AS TEXT
    NAME TEXT,           -- NAME AS TEXT, REQUIRED FIELD
    PHONE TEXT,            -- PHONE AS TEXT, UNIQUE CONSTRAINT INDICATED
    VEHICLETYPE TEXT,             -- VEHICLE TYPE AS TEXT
    LOCATIONID TEXT,              -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
    STATUS TEXT,                  -- STATUS AS TEXT
    GENDER TEXT,                  -- STATUS AS TEXT
    RATING TEXT,                  -- RATING AS TEXT
    CREATEDDATE TEXT,             -- CREATED DATE AS TEXT
    MODIFIEDDATE TEXT,            -- MODIFIED DATE AS TEXT

    -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
    STG_FILE_NAME TEXT,
    STG_FILE_LOAD_TS TIMESTAMP,
    STG_FILE_MD5 TEXT,
    COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
COMMENT = 'THIS IS THE DELIVERY STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE TEXT DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';

-- ----------------------------------------------------------------------------------------------------
-- CREATE DELIVERY_AGENT_SLV
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.DELIVERY_AGENT_SLV (
    DELIVERY_AGENT_SK INT AUTOINCREMENT PRIMARY KEY COMMENT 'SURROGATE KEY (EDW)', -- PRIMARY KEY WITH AUTO-INCREMENT
    DELIVERY_AGENT_ID INT NOT NULL UNIQUE COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',               -- DELIVERY AGENT ID AS INTEGER
    NAME STRING NOT NULL,                -- NAME AS STRING, REQUIRED FIELD
    PHONE STRING NOT NULL,                 -- PHONE AS STRING, UNIQUE CONSTRAINT
    VEHICLE_TYPE STRING NOT NULL,                 -- VEHICLE TYPE AS STRING
    LOCATION_ID_FK INT COMMENT 'LOCATION FK(SOURCE SYSTEM)',                     -- LOCATION ID AS INTEGER
    STATUS STRING,                       -- STATUS AS STRING
    GENDER STRING,                       -- GENDER AS STRING
    RATING NUMBER(4,2),                        -- RATING AS FLOAT
    CREATED_DT TIMESTAMP_NTZ,          -- CREATED DATE AS TIMESTAMP WITHOUT TIMEZONE
    MODIFIED_DT TIMESTAMP_NTZ,         -- MODIFIED DATE AS TIMESTAMP WITHOUT TIMEZONE

    -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
    STG_FILE_NAME STRING,               -- STAGING FILE NAME AS STRING
    STG_FILE_LOAD_TS TIMESTAMP,         -- STAGING FILE LOAD TIMESTAMP
    STG_FILE_MD5 STRING,                -- STAGING FILE MD5 HASH AS STRING
    COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- DATA COPY TIMESTAMP WITH DEFAULT VALUE
)
COMMENT = 'DELIVERY ENTITY UNDER CLEAN SCHEMA WITH APPROPRIATE DATA TYPE UNDER CLEAN SCHEMA LAYER, DATA IS POPULATED USING MERGE STATEMENT FROM THE STAGE LAYER LOCATION TABLE. THIS TABLE DOES NOT SUPPORT SCD2';

-- ----------------------------------------------------------------------------------------------------
-- CREATE DELIVERY_AGENT_GLD
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE GOLD.DIM_DELIVERY_AGENT (
    DELIVERY_AGENT_HK NUMBER PRIMARY KEY COMMENT 'DELIVERY AGEND DIM HK (EDW)',               -- HASH KEY FOR UNIQUE IDENTIFICATION
    DELIVERY_AGENT_ID NUMBER NOT NULL COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',               -- BUSINESS KEY
    NAME STRING NOT NULL,                   -- DELIVERY AGENT NAME
    PHONE STRING UNIQUE,                    -- PHONE NUMBER, UNIQUE
    VEHICLE_TYPE STRING,                    -- TYPE OF VEHICLE
    LOCATION_ID_FK NUMBER NOT NULL COMMENT 'LOCATION FK (SOURCE SYSTEM)',                     -- LOCATION ID
    STATUS STRING,                          -- CURRENT STATUS OF THE DELIVERY AGENT
    GENDER STRING,                          -- GENDER
    RATING NUMBER(4,2),                     -- RATING WITH ONE DECIMAL PRECISION
    EFF_START_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- EFFECTIVE START DATE
    EFF_END_DATE TIMESTAMP,                 -- EFFECTIVE END DATE (NULL FOR ACTIVE RECORD)
    IS_CURRENT BOOLEAN DEFAULT TRUE
)
COMMENT =  'DIM TABLE FOR DELIVERY AGENT ENTITY WITH SCD2 SUPPORT.';

-- ----------------------------------------------------------------------------------------------------
-- STAGE TO BRONZE
-- ----------------------------------------------------------------------------------------------------
COPY INTO BRONZE.DELIVERY_AGENT_BRZ (DELIVERY_AGENT_ID, NAME, PHONE, VEHICLETYPE, LOCATIONID,
                         STATUS, GENDER, RATING, CREATEDDATE, MODIFIEDDATE,
                         STG_FILE_NAME, STG_FILE_LOAD_TS, STG_FILE_MD5, COPY_DATA_TS)
FROM (
    SELECT
        T.$1::TEXT AS DELIVERY_AGENT_ID,
        T.$2::TEXT AS NAME,
        T.$3::TEXT AS PHONE,
        T.$4::TEXT AS VEHICLETYPE,
        T.$5::TEXT AS LOCATIONID,
        T.$6::TEXT AS STATUS,
        T.$7::TEXT AS GENDER,
        T.$8::TEXT AS RATING,
        T.$9::TEXT AS CREATEDDATE,
        T.$10::TEXT AS MODIFIEDDATE,
        METADATA$FILENAME AS _STG_FILE_NAME,
        METADATA$FILE_LAST_MODIFIED AS _STG_FILE_LOAD_TS,
        METADATA$FILE_CONTENT_KEY AS _STG_FILE_MD5,
        CURRENT_TIMESTAMP AS _COPY_DATA_TS
    FROM '@"SWIGGY"."BRONZE"."CSV_STG"/delivery_agent/delivery-agent-initial.csv' T
)
FILE_FORMAT = (FORMAT_NAME = 'BRONZE.CSV_FILE_FORMAT')
ON_ERROR = ABORT_STATEMENT;

-- ----------------------------------------------------------------------------------------------------
-- BRONZE TO STAGE
-- ----------------------------------------------------------------------------------------------------
MERGE INTO SILVER.DELIVERY_AGENT_SLV AS TARGET
USING BRONZE.DELIVERY_AGENT_BRZ AS SOURCE
ON TARGET.DELIVERY_AGENT_ID = SOURCE.DELIVERY_AGENT_ID
WHEN MATCHED THEN
    UPDATE SET
        TARGET.PHONE = SOURCE.PHONE,
        TARGET.VEHICLE_TYPE = SOURCE.VEHICLETYPE,
        TARGET.LOCATION_ID_FK = TRY_TO_NUMBER(SOURCE.LOCATIONID),
        TARGET.STATUS = SOURCE.STATUS,
        TARGET.GENDER = SOURCE.GENDER,
        TARGET.RATING = TRY_TO_DECIMAL(SOURCE.RATING,4,2),
        TARGET.CREATED_DT = TRY_TO_TIMESTAMP(SOURCE.CREATEDDATE),
        TARGET.MODIFIED_DT = TRY_TO_TIMESTAMP(SOURCE.MODIFIEDDATE),
        TARGET.STG_FILE_NAME = SOURCE.STG_FILE_NAME,
        TARGET.STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
        TARGET.STG_FILE_MD5 = SOURCE.STG_FILE_MD5,
        TARGET.COPY_DATA_TS = SOURCE.COPY_DATA_TS
WHEN NOT MATCHED THEN
    INSERT (
        DELIVERY_AGENT_ID,
        NAME,
        PHONE,
        VEHICLE_TYPE,
        LOCATION_ID_FK,
        STATUS,
        GENDER,
        RATING,
        CREATED_DT,
        MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    )
    VALUES (
        TRY_TO_NUMBER(SOURCE.DELIVERY_AGENT_ID),
        SOURCE.NAME,
        SOURCE.PHONE,
        SOURCE.VEHICLETYPE,
        TRY_TO_NUMBER(SOURCE.LOCATIONID),
        SOURCE.STATUS,
        SOURCE.GENDER,
        TRY_TO_NUMBER(SOURCE.RATING),
        TRY_TO_TIMESTAMP(SOURCE.CREATEDDATE),
        TRY_TO_TIMESTAMP(SOURCE.MODIFIEDDATE),
        SOURCE.STG_FILE_NAME,
        SOURCE.STG_FILE_LOAD_TS,
        SOURCE.STG_FILE_MD5,
        CURRENT_TIMESTAMP()
    );

-- ----------------------------------------------------------------------------------------------------
-- SILVER TO GOLD
-- ----------------------------------------------------------------------------------------------------
MERGE INTO GOLD.DIM_DELIVERY_AGENT AS TARGET
USING SILVER.DELIVERY_AGENT_SLV AS SOURCE
ON
    TARGET.DELIVERY_AGENT_ID = SOURCE.DELIVERY_AGENT_ID AND
    TARGET.NAME = SOURCE.NAME AND
    TARGET.PHONE = SOURCE.PHONE AND
    TARGET.VEHICLE_TYPE = SOURCE.VEHICLE_TYPE AND
    TARGET.LOCATION_ID_FK = SOURCE.LOCATION_ID_FK AND
    TARGET.STATUS = SOURCE.STATUS AND
    TARGET.GENDER = SOURCE.GENDER AND
    TARGET.RATING = SOURCE.RATING
WHEN MATCHED
    AND SOURCE.METADATA$ACTION = 'DELETE'
    AND SOURCE.METADATA$ISUPDATE = 'TRUE' THEN
    -- UPDATE THE EXISTING RECORD TO CLOSE ITS VALIDITY PERIOD
    UPDATE SET
        TARGET.EFF_END_DATE = CURRENT_TIMESTAMP,
        TARGET.IS_CURRENT = FALSE
WHEN NOT MATCHED
    AND SOURCE.METADATA$ACTION = 'INSERT'
    AND SOURCE.METADATA$ISUPDATE = 'TRUE' THEN
    -- INSERT NEW RECORD WITH CURRENT DATA AND NEW EFFECTIVE START DATE
    INSERT (
        DELIVERY_AGENT_HK,        -- HASH KEY
        DELIVERY_AGENT_ID,
        NAME,
        PHONE,
        VEHICLE_TYPE,
        LOCATION_ID_FK,
        STATUS,
        GENDER,
        RATING,
        EFF_START_DATE,
        EFF_END_DATE,
        IS_CURRENT
    )
    VALUES (
        HASH(SHA1_HEX(CONCAT(SOURCE.DELIVERY_AGENT_ID, SOURCE.NAME, SOURCE.PHONE,
            SOURCE.VEHICLE_TYPE, SOURCE.LOCATION_ID_FK, SOURCE.STATUS,
            SOURCE.GENDER, SOURCE.RATING))), -- HASH KEY
        DELIVERY_AGENT_ID,
        SOURCE.NAME,
        SOURCE.PHONE,
        SOURCE.VEHICLE_TYPE,
        LOCATION_ID_FK,
        SOURCE.STATUS,
        SOURCE.GENDER,
        SOURCE.RATING,
        CURRENT_TIMESTAMP,       -- EFFECTIVE START DATE
        NULL,                    -- EFFECTIVE END DATE (NULL FOR CURRENT RECORD)
        TRUE                    -- IS_CURRENT = TRUE FOR NEW RECORD
    )
WHEN NOT MATCHED
    AND SOURCE.METADATA$ACTION = 'INSERT'
    AND SOURCE.METADATA$ISUPDATE = 'FALSE' THEN
    -- INSERT NEW RECORD WITH CURRENT DATA AND NEW EFFECTIVE START DATE
    INSERT (
        DELIVERY_AGENT_HK,        -- HASH KEY
        DELIVERY_AGENT_ID,
        NAME,
        PHONE,
        VEHICLE_TYPE,
        LOCATION_ID_FK,
        STATUS,
        GENDER,
        RATING,
        EFF_START_DATE,
        EFF_END_DATE,
        IS_CURRENT
    )
    VALUES (
        HASH(SHA1_HEX(CONCAT(SOURCE.DELIVERY_AGENT_ID, SOURCE.NAME, SOURCE.PHONE,
            SOURCE.VEHICLE_TYPE, SOURCE.LOCATION_ID_FK, SOURCE.STATUS,
            SOURCE.GENDER, SOURCE.RATING))), -- HASH KEY
        SOURCE.DELIVERY_AGENT_ID,
        SOURCE.NAME,
        SOURCE.PHONE,
        SOURCE.VEHICLE_TYPE,
        SOURCE.LOCATION_ID_FK,
        SOURCE.STATUS,
        SOURCE.GENDER,
        SOURCE.RATING,
        CURRENT_TIMESTAMP,       -- EFFECTIVE START DATE
        NULL,                    -- EFFECTIVE END DATE (NULL FOR CURRENT RECORD)
        TRUE                   -- IS_CURRENT = TRUE FOR NEW RECORD
    );
-- ====================================================================================================