- =====================================================
-- SNOWFLAKE KAFKA USER SETUP
-- =====================================================
USE ROLE ACCOUNTADMIN;
USE DATABASE SWIGGY;
USE WAREHOUSE ADHOC_WH;

-- Create role for Kafka
CREATE ROLE IF NOT EXISTS KAFKA_CONNECTOR_ROLE;

-- Grant database and schema privileges
GRANT USAGE ON DATABASE SWIGGY TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON SCHEMA SILVER TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON WAREHOUSE ADHOC_WH TO ROLE KAFKA_CONNECTOR_ROLE;

-- Grant table privileges
GRANT CREATE TABLE ON SCHEMA SILVER TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE STAGE ON SCHEMA SILVER TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE PIPE ON SCHEMA SILVER TO ROLE KAFKA_CONNECTOR_ROLE;

-- Create user for Kafka Connect
CREATE USER KAFKA_CONNECT_USER
RSA_PUBLIC_KEY = '<RSA KEY>'
DEFAULT_ROLE = KAFKA_CONNECTOR_ROLE
DEFAULT_WAREHOUSE = ADHOC_WH
DEFAULT_NAMESPACE = SWIGGY.SILVER;

-- Grant necessary privileges to your Kafka Connect user
GRANT USAGE ON SCHEMA SWIGGY.SILVER TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE TABLE ON SCHEMA SWIGGY.SILVER TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE STAGE ON SCHEMA SWIGGY.SILVER TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE PIPE ON SCHEMA SWIGGY.SILVER TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON SCHEMA SWIGGY.GOLD TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE TABLE ON SCHEMA SWIGGY.GOLD TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE STAGE ON SCHEMA SWIGGY.GOLD TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE PIPE ON SCHEMA SWIGGY.GOLD TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA SWIGGY.GOLD TO ROLE KAFKA_CONNECTOR_ROLE;

-- Grant Access to SYSADMIN
-- Grant database access
GRANT USAGE ON DATABASE SWIGGY TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE SWIGGY TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA SWIGGY.SILVER TO ROLE SYSADMIN;

-- Grant table creation permissions
GRANT CREATE TABLE ON SCHEMA SWIGGY.SILVER TO ROLE SYSADMIN;
GRANT CREATE STAGE ON SCHEMA SWIGGY.SILVER TO ROLE SYSADMIN;
GRANT CREATE PIPE ON SCHEMA SWIGGY.SILVER TO ROLE SYSADMIN;

-- For Snowpipe Streaming (you're using this!)
GRANT CREATE STREAMLIT ON SCHEMA SWIGGY.SILVER TO ROLE SYSADMIN;

-- Grant write permissions
GRANT INSERT ON ALL TABLES IN SCHEMA SWIGGY.SILVER TO ROLE SYSADMIN;
GRANT UPDATE ON ALL TABLES IN SCHEMA SWIGGY.SILVER TO ROLE SYSADMIN;

-- Grant necessary privileges in Snowflake
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE SWIGGY TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA SWIGGY.SILVER TO ROLE SYSADMIN;
GRANT CREATE STAGE ON SCHEMA SWIGGY.SILVER TO ROLE SYSADMIN;
GRANT CREATE PIPE ON SCHEMA SWIGGY.SILVER TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA SWIGGY.SILVER TO ROLE SYSADMIN;

-- Grant role to user
GRANT ROLE KAFKA_CONNECTOR_ROLE TO USER KAFKA_CONNECT_USER;
ALTER USER KAFKA_CONNECT_USER SET DEFAULT_ROLE = KAFKA_CONNECTOR_ROLE;
GRANT ROLE SYSADMIN TO USER KAFKA_CONNECT_USER;
GRANT ROLE KAFKA_CONNECTOR_ROLE TO ROLE ACCOUNTADMIN;

-- Verify user creation
SHOW USERS LIKE 'KAFKA_CONNECT_USER';
DESC USER KAFKA_CONNECT_USER;

