-- ====================================================================================================
-- MENU
-- ====================================================================================================
-- CHANGE CONTEXT
USE DATABASE SWIGGY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;

-- ----------------------------------------------------------------------------------------------------
-- CREATE MENU_BRZ
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.MENU_BRZ (
    MENUID TEXT COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',                   -- PRIMARY KEY AS TEXT
    RESTAURANT_ID TEXT COMMENT 'RESTAURANT FK(SOURCE SYSTEM)',             -- FOREIGN KEY REFERENCE AS TEXT (NO CONSTRAINT IN SNOWFLAKE)
    ITEMNAME TEXT,                 -- ITEM NAME AS TEXT
    DESCRIPTION TEXT,              -- DESCRIPTION AS TEXT
    PRICE TEXT,                    -- PRICE AS TEXT (NO DECIMAL CONSTRAINT)
    CATEGORY TEXT,                 -- CATEGORY AS TEXT
    AVAILABILITY TEXT,             -- AVAILABILITY AS TEXT
    ITEMTYPE TEXT,                 -- ITEM TYPE AS TEXT
    CREATEDDATE TEXT,              -- CREATED DATE AS TEXT
    MODIFIEDDATE TEXT,             -- MODIFIED DATE AS TEXT
    -- AUDIT COLUMNS WITH APPROPRIATE DATA TYPES
    STG_FILE_NAME TEXT,
    STG_FILE_LOAD_TS TIMESTAMP,
    STG_FILE_MD5 TEXT,
    COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
COMMENT = 'THIS IS THE MENU STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE TEXT DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';

-- ----------------------------------------------------------------------------------------------------
-- CREATE MENU_SLV
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.MENU_SLV (
    MENU_SK INT AUTOINCREMENT PRIMARY KEY COMMENT 'SURROGATE KEY (EDW)',  -- AUTO-INCREMENTING PRIMARY KEY FOR INTERNAL TRACKING
    MENU_ID INT NOT NULL UNIQUE COMMENT 'PRIMARY KEY (SOURCE SYSTEM)' ,             -- UNIQUE AND NON-NULL MENU_ID
    RESTAURANT_ID_FK INT COMMENT 'RESTAURANT FK(SOURCE SYSTEM)' ,                      -- IDENTIFIER FOR THE RESTAURANT
    ITEM_NAME STRING NOT NULL,                        -- NAME OF THE MENU ITEM
    DESCRIPTION STRING NOT NULL,                     -- DESCRIPTION OF THE MENU ITEM
    PRICE DECIMAL(10, 2) NOT NULL,                   -- PRICE AS A NUMERIC VALUE WITH 2 DECIMAL PLACES
    CATEGORY STRING,                        -- FOOD CATEGORY (E.G., NORTH INDIAN)
    AVAILABILITY BOOLEAN,                   -- AVAILABILITY STATUS (TRUE/FALSE)
    ITEM_TYPE STRING,                        -- DIETARY CLASSIFICATION (E.G., VEGAN)
    CREATED_DT TIMESTAMP_NTZ,               -- DATE WHEN THE RECORD WAS CREATED
    MODIFIED_DT TIMESTAMP_NTZ,              -- DATE WHEN THE RECORD WAS LAST MODIFIED
    -- AUDIT COLUMNS FOR TRACEABILITY
    STG_FILE_NAME STRING,                  -- SOURCE FILE NAME
    STG_FILE_LOAD_TS TIMESTAMP_NTZ,        -- TIMESTAMP WHEN DATA WAS LOADED FROM THE STAGING LAYER
    STG_FILE_MD5 STRING,                   -- MD5 HASH OF THE SOURCE FILE
    COPY_DATA_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP -- TIMESTAMP WHEN DATA WAS COPIED TO THE CLEAN LAYER
)
COMMENT = 'MENU ENTITY UNDER CLEAN SCHEMA WITH APPROPRIATE DATA TYPE UNDER CLEAN SCHEMA LAYER, DATA IS POPULATED USING MERGE STATEMENT FROM THE STAGE LAYER LOCATION TABLE. THIS TABLE DOES NOT SUPPORT SCD2';

-- ----------------------------------------------------------------------------------------------------
-- CREATE DIM_MENU
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE GOLD.DIM_MENU (
    MENU_DIM_HK NUMBER PRIMARY KEY COMMENT 'MENU DIM HK (EDW)',                         -- HASH KEY GENERATED FOR MENU DIM TABLE
    MENU_ID INT NOT NULL COMMENT 'PRIMARY KEY (SOURCE SYSTEM)',                       -- UNIQUE AND NON-NULL MENU_ID
    RESTAURANT_ID_FK INT NOT NULL COMMENT 'RESTAURANT FK (SOURCE SYSTEM)',                          -- IDENTIFIER FOR THE RESTAURANT
    ITEM_NAME STRING,                            -- NAME OF THE MENU ITEM
    DESCRIPTION STRING,                         -- DESCRIPTION OF THE MENU ITEM
    PRICE DECIMAL(10, 2),                       -- PRICE AS A NUMERIC VALUE WITH 2 DECIMAL PLACES
    CATEGORY STRING,                            -- FOOD CATEGORY (E.G., NORTH INDIAN)
    AVAILABILITY BOOLEAN,                       -- AVAILABILITY STATUS (TRUE/FALSE)
    ITEM_TYPE STRING,                           -- DIETARY CLASSIFICATION (E.G., VEGAN)
    EFF_START_DATE TIMESTAMP_NTZ,               -- EFFECTIVE START DATE OF THE RECORD
    EFF_END_DATE TIMESTAMP_NTZ,                 -- EFFECTIVE END DATE OF THE RECORD
    IS_CURRENT BOOLEAN                         -- FLAG TO INDICATE IF THE RECORD IS CURRENT (TRUE/FALSE)
)
COMMENT = 'THIS TABLE STORES THE DIMENSION DATA FOR THE MENU ITEMS, TRACKING HISTORICAL CHANGES USING SCD TYPE 2. EACH MENU ITEM HAS AN EFFECTIVE START AND END DATE, WITH A FLAG INDICATING IF IT IS THE CURRENT RECORD OR HISTORICAL. THE HASH KEY (MENU_DIM_HK) IS GENERATED BASED ON MENU_ID AND RESTAURANT_ID.';

-- ----------------------------------------------------------------------------------------------------
-- STAGE TO BRONZE
-- ----------------------------------------------------------------------------------------------------
COPY INTO BRONZE.MENU_BRZ (MENUID, RESTAURANT_ID, ITEMNAME, DESCRIPTION, PRICE, CATEGORY,
                AVAILABILITY, ITEMTYPE, CREATEDDATE, MODIFIEDDATE,
                STG_FILE_NAME, STG_FILE_LOAD_TS, STG_FILE_MD5, COPY_DATA_TS)
FROM (
    SELECT
        T.$1::TEXT AS MENUID,
        T.$2::TEXT AS RESTAURANT_ID,
        T.$3::TEXT AS ITEMNAME,
        T.$4::TEXT AS DESCRIPTION,
        T.$5::TEXT AS PRICE,
        T.$6::TEXT AS CATEGORY,
        T.$7::TEXT AS AVAILABILITY,
        T.$8::TEXT AS ITEMTYPE,
        T.$9::TEXT AS CREATEDDATE,
        T.$10::TEXT AS MODIFIEDDATE,
        METADATA$FILENAME AS STG_FILE_NAME,
        METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
        METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
        CURRENT_TIMESTAMP AS COPY_DATA_TS
    FROM '@"SWIGGY"."BRONZE"."CSV_STG"/menu/menu-initial-load.csv' T
)
FILE_FORMAT = (FORMAT_NAME = 'BRONZE.CSV_FILE_FORMAT')
ON_ERROR = ABORT_STATEMENT;

-- ----------------------------------------------------------------------------------------------------
-- BRONZE TO SILVER
-- ----------------------------------------------------------------------------------------------------
MERGE INTO SILVER.MENU_SLV AS TARGET
USING (
    SELECT
        TRY_CAST(MENUID AS INT) AS MENU_ID,
        TRY_CAST(RESTAURANT_ID AS INT) AS RESTAURANT_ID_FK,
        TRIM(ITEMNAME) AS ITEM_NAME,
        TRIM(DESCRIPTION) AS DESCRIPTION,
        TRY_CAST(PRICE AS DECIMAL(10, 2)) AS PRICE,
        TRIM(CATEGORY) AS CATEGORY,
        CASE
            WHEN LOWER(AVAILABILITY) = 'TRUE' THEN TRUE
            WHEN LOWER(AVAILABILITY) = 'FALSE' THEN FALSE
            ELSE NULL
        END AS AVAILABILITY,
        TRIM(ITEMTYPE) AS ITEM_TYPE,
        TRY_CAST(CREATEDDATE AS TIMESTAMP_NTZ) AS CREATED_DT,  -- RENAMED COLUMN
        TRY_CAST(MODIFIEDDATE AS TIMESTAMP_NTZ) AS MODIFIED_DT, -- RENAMED COLUMN
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    FROM BRONZE.MENU_BRZ
) AS SOURCE
ON TARGET.MENU_ID = SOURCE.MENU_ID
WHEN MATCHED THEN
    UPDATE SET
        RESTAURANT_ID_FK = SOURCE.RESTAURANT_ID_FK,
        ITEM_NAME = SOURCE.ITEM_NAME,
        DESCRIPTION = SOURCE.DESCRIPTION,
        PRICE = SOURCE.PRICE,
        CATEGORY = SOURCE.CATEGORY,
        AVAILABILITY = SOURCE.AVAILABILITY,
        ITEM_TYPE = SOURCE.ITEM_TYPE,
        CREATED_DT = SOURCE.CREATED_DT,
        MODIFIED_DT = SOURCE.MODIFIED_DT,
        STG_FILE_NAME = SOURCE.STG_FILE_NAME,
        STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
        STG_FILE_MD5 = SOURCE.STG_FILE_MD5,
        COPY_DATA_TS = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (
        MENU_ID,
        RESTAURANT_ID_FK,
        ITEM_NAME,
        DESCRIPTION,
        PRICE,
        CATEGORY,
        AVAILABILITY,
        ITEM_TYPE,
        CREATED_DT,
        MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5,
        COPY_DATA_TS
    )
    VALUES (
        SOURCE.MENU_ID,
        SOURCE.RESTAURANT_ID_FK,
        SOURCE.ITEM_NAME,
        SOURCE.DESCRIPTION,
        SOURCE.PRICE,
        SOURCE.CATEGORY,
        SOURCE.AVAILABILITY,
        SOURCE.ITEM_TYPE,
        SOURCE.CREATED_DT,
        SOURCE.MODIFIED_DT,
        SOURCE.STG_FILE_NAME,
        SOURCE.STG_FILE_LOAD_TS,
        SOURCE.STG_FILE_MD5,
        CURRENT_TIMESTAMP
    );

-- ----------------------------------------------------------------------------------------------------
-- SILVER TO GOLD
-- ----------------------------------------------------------------------------------------------------
MERGE INTO
    GOLD.DIM_MENU AS TARGET
USING
    SILVER.MENU_SLV AS SOURCE
ON
    TARGET.MENU_ID = SOURCE.MENU_ID AND
    TARGET.RESTAURANT_ID_FK = SOURCE.RESTAURANT_ID_FK AND
    TARGET.ITEM_NAME = SOURCE.ITEM_NAME AND
    TARGET.DESCRIPTION = SOURCE.DESCRIPTION AND
    TARGET.PRICE = SOURCE.PRICE AND
    TARGET.CATEGORY = SOURCE.CATEGORY AND
    TARGET.AVAILABILITY = SOURCE.AVAILABILITY AND
    TARGET.ITEM_TYPE = SOURCE.ITEM_TYPE
WHEN MATCHED
    AND SOURCE.METADATA$ACTION = 'DELETE'
    AND SOURCE.METADATA$ISUPDATE = 'TRUE' THEN
    -- UPDATE THE EXISTING RECORD TO CLOSE ITS VALIDITY PERIOD
    UPDATE SET
        TARGET.EFF_END_DATE = CURRENT_TIMESTAMP(),
        TARGET.IS_CURRENT = FALSE
WHEN NOT MATCHED
    AND SOURCE.METADATA$ACTION = 'INSERT'
    AND SOURCE.METADATA$ISUPDATE = 'TRUE' THEN
    -- INSERT NEW RECORD WITH CURRENT DATA AND NEW EFFECTIVE START DATE
    INSERT (
        MENU_DIM_HK,               -- HASH KEY
        MENU_ID,
        RESTAURANT_ID_FK,
        ITEM_NAME,
        DESCRIPTION,
        PRICE,
        CATEGORY,
        AVAILABILITY,
        ITEM_TYPE,
        EFF_START_DATE,
        EFF_END_DATE,
        IS_CURRENT
    )
    VALUES (
        HASH(SHA1_HEX(CONCAT(SOURCE.MENU_ID, SOURCE.RESTAURANT_ID_FK,
            SOURCE.ITEM_NAME, SOURCE.DESCRIPTION, SOURCE.PRICE,
            SOURCE.CATEGORY, SOURCE.AVAILABILITY, SOURCE.ITEM_TYPE))),  -- HASH KEY
        SOURCE.MENU_ID,
        SOURCE.RESTAURANT_ID_FK,
        SOURCE.ITEM_NAME,
        SOURCE.DESCRIPTION,
        SOURCE.PRICE,
        SOURCE.CATEGORY,
        SOURCE.AVAILABILITY,
        SOURCE.ITEM_TYPE,
        CURRENT_TIMESTAMP(),       -- EFFECTIVE START DATE
        NULL,                      -- EFFECTIVE END DATE (NULL FOR CURRENT RECORD)
        TRUE                       -- IS_CURRENT = TRUE FOR NEW RECORD
    )
WHEN NOT MATCHED
    AND SOURCE.METADATA$ACTION = 'INSERT'
    AND SOURCE.METADATA$ISUPDATE = 'FALSE' THEN
    -- INSERT NEW RECORD WITH CURRENT DATA AND NEW EFFECTIVE START DATE
    INSERT (
        MENU_DIM_HK,               -- HASH KEY
        MENU_ID,
        RESTAURANT_ID_FK,
        ITEM_NAME,
        DESCRIPTION,
        PRICE,
        CATEGORY,
        AVAILABILITY,
        ITEM_TYPE,
        EFF_START_DATE,
        EFF_END_DATE,
        IS_CURRENT
    )
    VALUES (
        HASH(SHA1_HEX(CONCAT(SOURCE.MENU_ID, SOURCE.RESTAURANT_ID_FK,
            SOURCE.ITEM_NAME, SOURCE.DESCRIPTION, SOURCE.PRICE,
            SOURCE.CATEGORY, SOURCE.AVAILABILITY, SOURCE.ITEM_TYPE))),  -- HASH KEY
        SOURCE.MENU_ID,
        SOURCE.RESTAURANT_ID_FK,
        SOURCE.ITEM_NAME,
        SOURCE.DESCRIPTION,
        SOURCE.PRICE,
        SOURCE.CATEGORY,
        SOURCE.AVAILABILITY,
        SOURCE.ITEM_TYPE,
        CURRENT_TIMESTAMP(),       -- EFFECTIVE START DATE
        NULL,                      -- EFFECTIVE END DATE (NULL FOR CURRENT RECORD)
        TRUE                       -- IS_CURRENT = TRUE FOR NEW RECORD
    );
-- ====================================================================================================