-- ====================================================================================================
-- RESTAURANT
-- ====================================================================================================
-- CHANGE CONTEXT
USE ROLE ACCOUNTADMIN;
USE DATABASE SWIGGY;
USE SCHEMA BRONZE;
USE WAREHOUSE ADHOC_WH;

-- ----------------------------------------------------------------------------------------------------
-- CREATE RESTAURANT_BRZ
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.RESTAURANT_BRZ (
    RESTAURANT_ID TEXT,
    NAME TEXT ,                                                             -- RESTAURANT NAME, REQUIRED FIELD
    CUISINETYPE TEXT,                                                       -- TYPE OF CUISINE OFFERED
    PRICING_FOR_2 TEXT,                                                     -- PRICING FOR TWO PEOPLE AS TEXT
    RESTAURANT_PHONE TEXT WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),   -- PHONE NUMBER AS TEXT
    OPERATINGHOURS TEXT,                                                    -- RESTAURANT OPERATING HOURS
    LOCATIONID TEXT ,                                                       -- LOCATION ID, DEFAULT AS TEXT
    ACTIVEFLAG TEXT ,                                                       -- ACTIVE STATUS
    OPENSTATUS TEXT ,                                                       -- OPEN STATUS
    LOCALITY TEXT,                                                          -- LOCALITY AS TEXT
    RESTAURANT_ADDRESS TEXT,                                                -- ADDRESS AS TEXT
    LATITUDE TEXT,                                                          -- LATITUDE AS TEXT FOR PRECISION
    LONGITUDE TEXT,                                                         -- LONGITUDE AS TEXT FOR PRECISION
    CREATEDDATE TEXT,                                                       -- RECORD CREATION DATE
    MODIFIEDDATE TEXT,                                                      -- LAST MODIFIED DATE
    -- AUDIT COLUMNS FOR DEBUGGING
    STG_FILE_NAME TEXT,
    STG_FILE_LOAD_TS TIMESTAMP,
    STG_FILE_MD5 TEXT,
    COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
COMMENT = 'THIS IS THE RESTAURANT STAGE/RAW TABLE WHERE DATA WILL BE COPIED FROM INTERNAL STAGE USING COPY COMMAND. THIS IS AS-IS DATA REPRESETATION FROM THE SOURCE LOCATION. ALL THE COLUMNS ARE TEXT DATA TYPE EXCEPT THE AUDIT COLUMNS THAT ARE ADDED FOR TRACEABILITY.';

-- ----------------------------------------------------------------------------------------------------
-- CREATE RESTAURANT_SLV
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.RESTAURANT_SLV (
    RESTAURANT_SK NUMBER AUTOINCREMENT PRIMARY KEY,              -- PRIMARY KEY WITH AUTO-INCREMENT
    RESTAURANT_ID NUMBER UNIQUE,                                 -- RESTAURANT ID WITHOUT AUTO-INCREMENT
    NAME STRING(100) NOT NULL,                                   -- RESTAURANT NAME, REQUIRED FIELD
    CUISINE_TYPE STRING,                                         -- TYPE OF CUISINE OFFERED
    PRICING_FOR_TWO NUMBER(10, 2),                               -- PRICING FOR TWO PEOPLE, UP TO 10 DIGITS WITH 2 DECIMAL PLACES
    RESTAURANT_PHONE STRING(15) WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),                                 -- PHONE NUMBER, SUPPORTS 10-DIGIT OR INTERNATIONAL FORMAT
    OPERATING_HOURS STRING(100),                                  -- RESTAURANT OPERATING HOURS
    LOCATION_ID_FK NUMBER,                                       -- REFERENCE ID FOR LOCATION, DEFAULTED TO 1
    ACTIVE_FLAG STRING(10),                                      -- INDICATES IF THE RESTAURANT IS ACTIVE
    OPEN_STATUS STRING(10),                                      -- INDICATES IF THE RESTAURANT IS CURRENTLY OPEN
    LOCALITY STRING(100),                                        -- LOCALITY OF THE RESTAURANT
    RESTAURANT_ADDRESS STRING,                                   -- ADDRESS OF THE RESTAURANT, SUPPORTS LONGER TEXT
    LATITUDE NUMBER(9, 6),                                       -- LATITUDE WITH 6 DECIMAL PLACES FOR PRECISION
    LONGITUDE NUMBER(9, 6),                                      -- LONGITUDE WITH 6 DECIMAL PLACES FOR PRECISION
    CREATED_DT TIMESTAMP_TZ,                                     -- RECORD CREATION DATE
    MODIFIED_DT TIMESTAMP_TZ,                                    -- LAST MODIFIED DATE, ALLOWS NULL IF NOT MODIFIED
    -- ADDITIONAL AUDIT COLUMNS
    STG_FILE_NAME STRING,                                       -- FILE NAME FOR AUDIT
    STG_FILE_LOAD_TS TIMESTAMP_NTZ,                             -- FILE LOAD TIMESTAMP FOR AUDIT
    STG_FILE_MD5 STRING,                                        -- MD5 HASH FOR FILE CONTENT FOR AUDIT
    COPY_DATA_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP        -- TIMESTAMP WHEN DATA IS COPIED, DEFAULTS TO CURRENT TIMESTAMP
)
COMMENT = 'RESTAURANT ENTITY UNDER CLEAN SCHEMA WITH APPROPRIATE DATA TYPE UNDER CLEAN SCHEMA LAYER, DATA IS POPULATED USING MERGE STATEMENT FROM THE STAGE LAYER LOCATION TABLE. THIS TABLE DOES NOT SUPPORT SCD2';

-- ----------------------------------------------------------------------------------------------------
-- CREATE RESTAURANT_GLD
-- ----------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE GOLD.DIM_RESTAURANT (
    RESTAURANT_HK NUMBER PRIMARY KEY,                   -- HASH KEY FOR THE RESTAURANT LOCATION
    RESTAURANT_ID NUMBER,                   -- RESTAURANT ID WITHOUT AUTO-INCREMENT
    NAME STRING(100),                       -- RESTAURANT NAME
    CUISINE_TYPE STRING,                    -- TYPE OF CUISINE OFFERED
    PRICING_FOR_TWO NUMBER(10, 2),          -- PRICING FOR TWO PEOPLE
    RESTAURANT_PHONE STRING(15) WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),            -- RESTAURANT PHONE NUMBER
    OPERATING_HOURS STRING(100),            -- RESTAURANT OPERATING HOURS
    LOCATION_ID_FK NUMBER,                  -- FOREIGN KEY REFERENCE TO LOCATION
    ACTIVE_FLAG STRING(10),                 -- INDICATES IF THE RESTAURANT IS ACTIVE
    OPEN_STATUS STRING(10),                 -- INDICATES IF THE RESTAURANT IS CURRENTLY OPEN
    LOCALITY STRING(100),                   -- LOCALITY OF THE RESTAURANT
    RESTAURANT_ADDRESS STRING,              -- FULL ADDRESS OF THE RESTAURANT
    LATITUDE NUMBER(9, 6),                  -- LATITUDE FOR THE RESTAURANT'S LOCATION
    LONGITUDE NUMBER(9, 6),                 -- LONGITUDE FOR THE RESTAURANT'S LOCATION
    EFF_START_DATE TIMESTAMP_TZ,            -- EFFECTIVE START DATE FOR THE RECORD
    EFF_END_DATE TIMESTAMP_TZ,              -- EFFECTIVE END DATE FOR THE RECORD (NULL IF ACTIVE)
    IS_CURRENT BOOLEAN                     -- INDICATES WHETHER THE RECORD IS THE CURRENT VERSION
)
COMMENT = 'DIMENSIONAL TABLE FOR RESTAURANT ENTITY WITH HASH KEYS AND SCD ENABLED.';

-- ----------------------------------------------------------------------------------------------------
-- STAGE TO BRONZE
-- ----------------------------------------------------------------------------------------------------
COPY INTO BRONZE.RESTAURANT_BRZ (RESTAURANT_ID, NAME, CUISINETYPE, PRICING_FOR_2, RESTAURANT_PHONE,
                      OPERATINGHOURS, LOCATIONID, ACTIVEFLAG, OPENSTATUS,
                      LOCALITY, RESTAURANT_ADDRESS, LATITUDE, LONGITUDE,
                      CREATEDDATE, MODIFIEDDATE,
                      STG_FILE_NAME, STG_FILE_LOAD_TS, STG_FILE_MD5, COPY_DATA_TS)
FROM (
    SELECT
        T.$1::TEXT AS RESTAURANTID,        -- RESTAURANTID AS THE FIRST COLUMN
        T.$2::TEXT AS NAME,
        T.$3::TEXT AS CUISINETYPE,
        T.$4::TEXT AS PRICING_FOR_2,
        T.$5::TEXT AS RESTAURANT_PHONE,
        T.$6::TEXT AS OPERATINGHOURS,
        T.$7::TEXT AS LOCATIONID,
        T.$8::TEXT AS ACTIVEFLAG,
        T.$9::TEXT AS OPENSTATUS,
        T.$10::TEXT AS LOCALITY,
        T.$11::TEXT AS RESTAURANT_ADDRESS,
        T.$12::TEXT AS LATITUDE,
        T.$13::TEXT AS LONGITUDE,
        T.$14::TEXT AS CREATEDDATE,
        T.$15::TEXT AS MODIFIEDDATE,
        -- AUDIT COLUMNS FOR TRACKING & DEBUGGING
        METADATA$FILENAME AS STG_FILE_NAME,
        METADATA$FILE_LAST_MODIFIED AS STG_FILE_LOAD_TS,
        METADATA$FILE_CONTENT_KEY AS STG_FILE_MD5,
        CURRENT_TIMESTAMP() AS COPY_DATA_TS
     FROM '@"SWIGGY"."BRONZE"."CSV_STG"/restaurant/restaurant-delhi+NCR.csv' T
)
FILE_FORMAT = (FORMAT_NAME = 'BRONZE.CSV_FILE_FORMAT')
ON_ERROR = ABORT_STATEMENT;

-- ----------------------------------------------------------------------------------------------------
-- BRONZE TO SILVER
-- ----------------------------------------------------------------------------------------------------
-- FOLLOWING IS THE INSERT STATEMENT..
INSERT INTO SILVER.RESTAURANT_SLV (
    RESTAURANT_ID,
    NAME,
    CUISINE_TYPE,
    PRICING_FOR_TWO,
    RESTAURANT_PHONE,
    OPERATING_HOURS,
    LOCATION_ID_FK,
    ACTIVE_FLAG,
    OPEN_STATUS,
    LOCALITY,
    RESTAURANT_ADDRESS,
    LATITUDE,
    LONGITUDE,
    CREATED_DT,
    MODIFIED_DT,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5
)
SELECT
    TRY_CAST(RESTAURANT_ID AS NUMBER) AS RESTAURANT_ID,
    TRY_CAST(NAME AS STRING) AS NAME,
    TRY_CAST(CUISINETYPE AS STRING) AS CUISINE_TYPE,
    TRY_CAST(PRICING_FOR_2 AS NUMBER(10, 2)) AS PRICING_FOR_TWO,
    TRY_CAST(RESTAURANT_PHONE AS STRING) AS RESTAURANT_PHONE,
    TRY_CAST(OPERATINGHOURS AS STRING) AS OPERATING_HOURS,
    TRY_CAST(LOCATIONID AS NUMBER) AS LOCATION_ID_FK,
    TRY_CAST(ACTIVEFLAG AS STRING) AS ACTIVE_FLAG,
    TRY_CAST(OPENSTATUS AS STRING) AS OPEN_STATUS,
    TRY_CAST(LOCALITY AS STRING) AS LOCALITY,
    TRY_CAST(RESTAURANT_ADDRESS AS STRING) AS RESTAURANT_ADDRESS,
    TRY_CAST(LATITUDE AS NUMBER(9, 6)) AS LATITUDE,
    TRY_CAST(LONGITUDE AS NUMBER(9, 6)) AS LONGITUDE,
    TRY_TO_TIMESTAMP_NTZ(CREATEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF9') AS CREATED_DT,
    TRY_TO_TIMESTAMP_NTZ(MODIFIEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF9') AS MODIFIED_DT,
    STG_FILE_NAME,
    STG_FILE_LOAD_TS,
    STG_FILE_MD5
FROM
    BRONZE.RESTAURANT_BRZ;

-- ----------------------------------------------------------------------------------------------------
-- SILVER TO GOLD
-- ----------------------------------------------------------------------------------------------------
MERGE INTO SILVER.RESTAURANT_SLV AS TARGET
USING (
    SELECT
        TRY_CAST(RESTAURANT_ID AS NUMBER) AS RESTAURANT_ID,
        TRY_CAST(NAME AS STRING) AS NAME,
        TRY_CAST(CUISINETYPE AS STRING) AS CUISINE_TYPE,
        TRY_CAST(PRICING_FOR_2 AS NUMBER(10, 2)) AS PRICING_FOR_TWO,
        TRY_CAST(RESTAURANT_PHONE AS STRING) AS RESTAURANT_PHONE,
        TRY_CAST(OPERATINGHOURS AS STRING) AS OPERATING_HOURS,
        TRY_CAST(LOCATIONID AS NUMBER) AS LOCATION_ID_FK,
        TRY_CAST(ACTIVEFLAG AS STRING) AS ACTIVE_FLAG,
        TRY_CAST(OPENSTATUS AS STRING) AS OPEN_STATUS,
        TRY_CAST(LOCALITY AS STRING) AS LOCALITY,
        TRY_CAST(RESTAURANT_ADDRESS AS STRING) AS RESTAURANT_ADDRESS,
        TRY_CAST(LATITUDE AS NUMBER(9, 6)) AS LATITUDE,
        TRY_CAST(LONGITUDE AS NUMBER(9, 6)) AS LONGITUDE,
        TRY_TO_TIMESTAMP_NTZ(CREATEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF9') AS CREATED_DT,
        TRY_TO_TIMESTAMP_NTZ(MODIFIEDDATE, 'YYYY-MM-DD HH24:MI:SS.FF9') AS MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5
    FROM
        BRONZE.RESTAURANT_BRZ
) AS SOURCE
ON TARGET.RESTAURANT_ID = SOURCE.RESTAURANT_ID
WHEN MATCHED THEN
    UPDATE SET
        TARGET.NAME = SOURCE.NAME,
        TARGET.CUISINE_TYPE = SOURCE.CUISINE_TYPE,
        TARGET.PRICING_FOR_TWO = SOURCE.PRICING_FOR_TWO,
        TARGET.RESTAURANT_PHONE = SOURCE.RESTAURANT_PHONE,
        TARGET.OPERATING_HOURS = SOURCE.OPERATING_HOURS,
        TARGET.LOCATION_ID_FK = SOURCE.LOCATION_ID_FK,
        TARGET.ACTIVE_FLAG = SOURCE.ACTIVE_FLAG,
        TARGET.OPEN_STATUS = SOURCE.OPEN_STATUS,
        TARGET.LOCALITY = SOURCE.LOCALITY,
        TARGET.RESTAURANT_ADDRESS = SOURCE.RESTAURANT_ADDRESS,
        TARGET.LATITUDE = SOURCE.LATITUDE,
        TARGET.LONGITUDE = SOURCE.LONGITUDE,
        TARGET.CREATED_DT = SOURCE.CREATED_DT,
        TARGET.MODIFIED_DT = SOURCE.MODIFIED_DT,
        TARGET.STG_FILE_NAME = SOURCE.STG_FILE_NAME,
        TARGET.STG_FILE_LOAD_TS = SOURCE.STG_FILE_LOAD_TS,
        TARGET.STG_FILE_MD5 = SOURCE.STG_FILE_MD5
WHEN NOT MATCHED THEN
    INSERT (
        RESTAURANT_ID,
        NAME,
        CUISINE_TYPE,
        PRICING_FOR_TWO,
        RESTAURANT_PHONE,
        OPERATING_HOURS,
        LOCATION_ID_FK,
        ACTIVE_FLAG,
        OPEN_STATUS,
        LOCALITY,
        RESTAURANT_ADDRESS,
        LATITUDE,
        LONGITUDE,
        CREATED_DT,
        MODIFIED_DT,
        STG_FILE_NAME,
        STG_FILE_LOAD_TS,
        STG_FILE_MD5
    )
    VALUES (
        SOURCE.RESTAURANT_ID,
        SOURCE.NAME,
        SOURCE.CUISINE_TYPE,
        SOURCE.PRICING_FOR_TWO,
        SOURCE.RESTAURANT_PHONE,
        SOURCE.OPERATING_HOURS,
        SOURCE.LOCATION_ID_FK,
        SOURCE.ACTIVE_FLAG,
        SOURCE.OPEN_STATUS,
        SOURCE.LOCALITY,
        SOURCE.RESTAURANT_ADDRESS,
        SOURCE.LATITUDE,
        SOURCE.LONGITUDE,
        SOURCE.CREATED_DT,
        SOURCE.MODIFIED_DT,
        SOURCE.STG_FILE_NAME,
        SOURCE.STG_FILE_LOAD_TS,
        SOURCE.STG_FILE_MD5
    );
-- ====================================================================================================

SELECT * FROM BRONZE.RESTAURANT_BRZ;
SELECT * FROM SILVER.RESTAURANT_SLV;
SELECT * FROM GOLD.DIM_RESTAURANT;